var companies = [];
var departments = [];
var titles = [
        'Advanced',
        'Basic',
        'Incubated',
        'Premium',
        'Standard',
]; var domains = [
        'AgriFood',
        'AI',
        'Cities',
        'Community',
        'Computer vision &amp; Mixed Reality',
        'Culture',
        'Destinations',
        'eGovernance',
        'eHealth',
        'Energy',
        'Environment',
        'Heritage',
        'Industry',
        'Livestock',
        'Logistics',
        'Manufacturing',
        'Mobility',
        'Multidomain',
        'Ports',
        'Resources',
        'Robotics',
        'Safet',
        'Sea',
        'Security',
        'Space',
        'Sustainability',
        'Territories',
        'Territory',
        'Tourism',
        'Transportation',
        'Villages',
        'Water',
]; var countries = [
        'Argentina',
        'Austria',
        'Brazil',
        'Canada',
        'Colombia',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Italy',
        'Japan',
        'Mexico',
        'Morocco',
        'Netherlands',
        'Norway',
        'Portugal',
        'Saudi Arabia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Tunisia',
        'Ukraine',
        'Uruguay',
        'USA',
]; 
