var companies = [];
var departments = [];
var titles = [
        'Advanced',
        'Basic',
        'Incubated',
        'Premium',
        'Standard',
]; var domains = [
        'AgriFood',
        'Agrifood',
        'AI',
        'Cities',
        'Community',
        'Computer vision &amp; Mixed Reality',
        'Culture',
        'eGovernance',
        'eHealth',
        'Energy',
        'Environment',
        'Heritage',
        'Industry',
        'Industry 4.0',
        'Logistics',
        'Manufacturing',
        'Mobility',
        'Multidomain',
        'Ports',
        'Precision Agriculture and Livestock',
        'Renewable Energies and Resources',
        'Robotics',
        'Safety and Security',
        'Sea',
        'Smart Cities',
        'Smart Destinations',
        'Space',
        'Sustainability',
        'Territory',
        'Tourism',
        'Transportation',
        'Villages',
        'Water',
]; var countries = [
        'Argentina',
        'Austria',
        'Brazil',
        'Canada',
        'Colombia',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'Italy',
        'Japan',
        'Mexico',
        'Morocco',
        'Netherlands',
        'Norway',
        'Portugal',
        'Saudi Arabia',
        'Spain',
        'Sweden',
        'Switzerland',
        'Tunisia',
        'Ukraine',
        'Uruguay',
        'USA',
]; 
