var companies = [
        'ADDIX',
        'AWS',
        'City of Herne',
        'Engineering',
        'Hopu – Libelium',
        'Madinah Region Development Authority',
        'MediTech',
        'NEC',
        'Red Hat',
        'Secmotic',
        'TeamDev',
        'Telefonica',
        'Ubiwhere',
]; var departments = [
]; var domains = [
        'Gold',
        'Platinum',
]; var titles = [
        'CDO',
        'CEO',
        'Co-Founder',
        'CSO',
        'Director',
        'Fellow',
        'General Manager',
        'Head of Unit',
        'IoT Specialist',
        'Managing Director',
        'Smart Cities Specialist',
]; var countries = [
        'France',
        'Germany',
        'Italy',
        'Japan',
        'Portugal',
        'Saudi Arabia',
        'Spain',
]; var modalData = [
    { name: "Dario Avallone", img: "https://www.fiware.org/wp-content/directories/people/images/200px/dario-avallone.jpg", position: "Research and Development Director", company: "Engineering S.p.A.", "company-link": "https://www.eng.it/en/",
    content: "Straight after getting his degree in Computer Science, Dario joined Engineering Ingegneria Informatica S.p.A’s R&amp;D Laboratory, where he has so far held different successful positions. In 2000, Dario became the Director of the R&amp;D division, aiming to push innovation into the large Engineering Group. During his professional career, Dario has been directly involved in different research initiatives, holding both managerial and technical responsibilities. He is also the author of different publications and articles and has co-authored the book “The Renaissance of Legacy Systems”.", linkedin: "https://www.linkedin.com/in/dario-avallone-428934a/", twitter: "", domain: "Platinum", location: "Italy",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Italy.png", },
    { name: "Andrea Battaglia", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-battaglia.jpg", position: "Head of Edge Computing &amp; AI Business Development", company: "Red Hat", "company-link": "https://www.redhat.com/en",
    content: "Andrea joined Red Hat in January 2015 and currently leads the Business Development of Edge Computing and AI ecosystems in the EMEA region. Andrea’s mission is to help customers solve their business and technical challenges together with the Red Hat Partner Ecosystem in the Edge Computing and AI space, incubating solutions, and going to market together. Andrea is also a Digital transformation expert with a strong technical background, thanks to his previous roles as Tech Lead of EMEA Services for Digital Transformation and EMEA Ecosystem Development Manager for Digital Transformation and Edge Computing. Andrea Is an animal, sport, and food lover, passionate about personal relationships and hungry for business and technical knowledge.", linkedin: "https://www.linkedin.com/in/abattagl/", twitter: "", domain: "Platinum", location: "Italy",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Italy.png", },
    { name: "Ali Benfattoum", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ali-benfattoum.jpg", position: "IoT &amp; Smart Cities Specialist", company: "AWS", "company-link": "https://aws.amazon.com/",
    content: "Ali Benfattoum is a Technology Evangelist for IoT and Smart Cities at Amazon Web Services. With over 12 years of experience in IoT and Smart Cities, Ali brings his technical expertise to enable and help customers and partners to accelerate their IoT and Smart Cities projects. Ali also holds an executive MBA, giving him the ability to zoom out and help customers and partners at a strategic level.", linkedin: "https://www.linkedin.com/in/alibenfattoum/", twitter: "https://twitter.com/alifrugal", domain: "Platinum", location: "France",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_France.png", },
    { name: "José Benitez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-benitez.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "Secmotic", "company-link": "https://secmotic.com/",
    content: "Jose has been Secmotic’s CEO since 2014 and founder of FIWOO, a smart city platform based on FIWARE, created in 2021. He has been a member of the FIWARE Board of Directors since 2018, being keen at any moment in time to represent the vision of SMEs and their interests. Jose is a vibrant and active player in the FIWARE Community and is deeply motivated bringing in cutting edge innovation technologies. As a Telecommunications Engineer, he is continuously investigating what’s happening in the space of data acquisition through wireless communications such as 5G, LoRA, WiFi, LTE, among others.", linkedin: "https://www.linkedin.com/in/jose-benitez-secmotic", twitter: "https://twitter.com/josesecmotic", domain: "Gold", location: "Spain",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Spain.png", },
    { name: "Agustin Cardenas Fernandez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/agustin-cardenas-fernandez.jpg", position: "Director of Company Business Transformation", company: "Telefonica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/agucardenas/", twitter: "https://twitter.com/agucardenas", domain: "Platinum", location: "Spain",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Spain.png", },
    { name: "Rui Costa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/rui-costa.jpg", position: "Chief Executive Officer", company: "Ubiwhere", "company-link": "https://www.ubiwhere.com/",
    content: "", linkedin: "https://www.linkedin.com/in/ruiarnaldo/", twitter: "", domain: "Gold", location: "Portugal",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Portugal.png", },
    { name: "Andrea Cruciani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-cruciani.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "TeamDev", "company-link": "https://www.teamdev.it/en/",
    content: "Andrea is the Agricolus co-founder and CEO, member of FIWARE Foundation BoD, Chairman of the FIWARE Smart AgriFood MSC. He runs the international business area and the financial aspects of the company and he has a technical background and experience in applications Development, Enterprise Architectures, Cloud Computing, and GIS. Andrea is involved in Innovative Startup Evolution and scaleup, during the years he worked with Public Administration, multinational companies, NGOs, and SMEs. He is a speaker for several universities and public events where he is invited to discuss entrepreneurship and digital transformation, and he is a contributor in several technical articles and publications about agritech.", linkedin: "https://www.linkedin.com/in/andreacruciani/", twitter: "https://twitter.com/kokkete", domain: "Gold", location: "Italy",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Italy.png", },
    { name: "Angelo Giuliana", img: "https://www.fiware.org/wp-content/directories/people/images/200px/angelo-giuliana.jpg", position: "General Manager", company: "MediTech", "company-link": "https://meditech4.com/",
    content: "Angelo Giuliana has many years of experience in commercial development and sales in IT companies of international scope, where he has held increasing managerial roles up to dealing with EMEA sales management. Giuliana has long-term experience in R&amp;D, has been a consultant to the European Commission for H2020 projects, and has been involved in innovation for some time. His vocation for technology transfer leads him to be a founding member of some innovative startups both in the ICT and manufacturing sectors. Angelo currently plays the role of General Manager of the MISE Competence Center for South Italy – Meditech. He graduated with a degree in Physics in 1982.", linkedin: "https://www.linkedin.com/in/angelogiuliana/", twitter: "https://twitter.com/dirgenmeditech", domain: "Gold", location: "Italy",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Italy.png", },
    { name: "Pierre Golz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/pierre-golz.jpg", position: "Chief Digital Officer", company: "City of Herne", "company-link": "https://www.herne.de/",
    content: "After getting his diploma as a public administration specialist, Pierre joined the city as an organizational developer and change manager. Since 2013, he has been working on projects focused on digitization and process management, and, at the age of 31, Pierre is the city’s youngest CDO to date. Pierre is also a lecturer in E-Government, Digitization, and Knowledge Management (among other areas) and feels that being able to combine science, economy and public management adds considerably to his career and role within the city.", linkedin: "https://www.linkedin.com/in/pierre-golz-311396156/", twitter: "", domain: "Gold", location: "Germany",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Germany.png", },
    { name: "Antonio Jara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonio-jara.jpg", position: "Chief Scientific Officer", company: "Hopu – Libelium", "company-link": "https://hopu.eu/",
    content: "Antonio has a PhD from the University of Murcia (Spain) and a MBA from the ENAE business school and UCAM (2012). He has received entrepreneurship awards from ENAE, emprendeGo, IPSO Alliance Award for its disruptive innovation in the IoT. As part of HOP Ubiquitous, Jara is focused on the Smart Cities market with solutions for citizens engagements, tourism, active participation, physical web and environmental monitoring (air quality sensors) in projects such as ENIAC SAFESENS, interoperability / pilots (SmartSDK, Synchronicity, Organicity, BeinCPPS) and also in several actions related to security/privacy (INPUT and FORTIKA).", linkedin: "https://www.linkedin.com/in/jara-libelium/", twitter: "https://twitter.com/antonio_jara", domain: "Gold", location: "Spain",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Spain.png", },
    { name: "Abdulmajeed Mangara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/abdulmajeed-mangara.jpg", position: "Smart City Program Director", company: "Madinah Region Development Authority", "company-link": "https://www.mda.gov.sa/",
    content: "Eng. Abdulmajeed Mangara, is the Smart City Program Director at Madinah Region Development Authority in Saudi Arabia. He pioneers the development of a comprehensive approach to transform Madinah into one of a leading smart city worldwide, while focusing on its religious and cultural identity. The approach he designed for Madinah consists of three strategic tracks: the smart city framework and strategy, the city innovation labs, and the smart city platform. Under his leadership, Madinah is among the first Saudi cities to develop a cohesive smart city strategy that aspires to transform Madinah into the most tranquil smart city in the world. The strategy includes six priority sectors for Madinah. He established Madinah Innovation Labs as the sandbox to develop Madinah’s solutions to address its pan-city or area-based challenges. Moreover, he led the team of experts to design, develop, and implement Raseel Platform in Madinah as the first smart city platform in Saudi Arabia.", linkedin: "https://www.linkedin.com/in/abdulmajeedsaud/", twitter: "", domain: "Platinum", location: "Saudi Arabia",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_SaudiArabia.png", },
    { name: "Yasunori Mochizuki", img: "https://www.fiware.org/wp-content/directories/people/images/200px/yasunori-mochizuki.jpg", position: "NEC Fellow", company: "NEC Corporation", "company-link": "https://www.nec.com/",
    content: "Yasunori joined NEC in 1987, straight after concluding his PhD in Electronics Engineering. He went on to spend over two decades at NEC’s corporate R&amp;D center, first as a research scientist and later as a department manager, gaining broader technical expertise, including solid-state physics, semiconductor devices/LSIs, and computer science. Later in 2013, Yasunori started working at NEC’s newly-created Business Innovation Unit. As a senior vice president, he was responsible for the corporate-wide technology strategy and IoT business strategy. His current title of NEC Fellow means that he actively participates in innovation policy proposals, global ecosystem building related to smart society, and digital transformation. He is also a BoD member of FIWARE Foundation, World Economic Forum. Fellow, and member of Business at OECD (BIAC) Committee for Digital Economy Policy.", linkedin: "https://www.linkedin.com/in/yasunori-mochizuki-93bab674/", twitter: "https://twitter.com/yasunorimochiz", domain: "Platinum", location: "Japan",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Japan.png", },
    { name: "Björn Schwarze", img: "https://www.fiware.org/wp-content/directories/people/images/200px/bjorn-schwarze.jpg", position: "Managing Director", company: "ADDIX", "company-link": "https://www.addix.net/",
    content: "", linkedin: "https://www.linkedin.com/in/bjoernschw/", twitter: "", domain: "Gold", location: "Germany",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag/flag_Germany.png", },
];