var companies = [
        'ATB Bremen',
        'Atos',
        'Austrian Ministry of Finance',
        'AWS',
        'CARTIF',
        'City of Herne',
        'Easy Global Market',
        'Engineering',
        'FIWARE Foundation',
        'Fraunhofer ISST',
        'FundingBox',
        'Gaia-X',
        'Hochschule Bochum',
        'Human Future',
        'IDSA',
        'Innovalia',
        'ISDI Accelerator',
        'Joanneum Research',
        'JRC – EC',
        'KMD',
        'Latitudo 40',
        'Libelium',
        'NEC Lab Europe',
        'TeamDev',
        'The Lisbon Council',
        'Universidad Politécnica de Madrid',
        'University of Cantabria',
        'Université Lumière Lyon 2',
        'WOBCOM',
        'Zabala',
]; var departments = [
]; var domains = [
]; var titles = [
        'Architect',
        'Associate Professor',
        'CDO',
        'CEO',
        'CMO',
        'Co-Founder',
        'Consultant',
        'Coordinator',
        'CSO',
        'CTO',
        'Data Modeling Expert',
        'Director',
        'Evangelist',
        'Founder',
        'Full Professor',
        'Head of Communications',
        'Head of Communities',
        'Head of IoT',
        'Manager',
        'Managing Director',
        'Marketplace Manager',
        'Project Portfolio Leader',
        'R&amp;D Manager',
        'Research Manager',
        'Researcher',
        'Sales Manager',
        'State Secretary',
        'Technical Expert',
        'Technical Lead',
        'VP',
]; var countries = [
]; var modalData = [
    { name: "Alberto Abella", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alberto-abella.jpg", position: "Data Modeling Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Alberto Abella (m) is PhD in Business (Open data) and Telecommunications Engineer and Master in Total Quality Management, Business Administration and Business Organization. He works as a Data Modelling Expert and Technical Evangelist at FIWARE and currently is the responsible person for the smart data models initiative.", linkedin: "https://www.linkedin.com/in/albertoabella/", twitter: "https://twitter.com/aabella", domain: "", location: "",
    flag: "", },
    { name: "Ulrich Ahle", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ulrich-ahle.jpg", position: "Chief Executive Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Ulrich Ahle (m) is a reputed executive in the industrial sector, formerly Vice President and leader of Manufacturing, Retail &amp; Transportation business and responsible for Industry 4.0 at Atos in Germany. He is also founder and member of the Board of the International Data Spaces Association in Germany and served 16 years in the Board of prostep ivip, until April 2018. After an apprenticeship as toolmaker at Hella KG, he studied Mechanical Engineering at the University of Paderborn. In his career, Ulrich held several positions as development engineer, Director of PLM services, Sales Director and Vice President. He has been part of Nixdorf Computer AG, Siemens and Atos. Since January 2017, Ulrich acts as Chief Executive Officer of FIWARE Foundation.", linkedin: "https://de.linkedin.com/in/ahlefiware", twitter: "https://twitter.com/UlrichAhle", domain: "", location: "",
    flag: "", },
    { name: "Yasser Alsaied", img: "https://www.fiware.org/wp-content/directories/people/images/200px/yasser-alsaied.jpg", position: "VP &amp; Head of AWS IoT", company: "AWS", "company-link": "https://aws.amazon.com/",
    content: "", linkedin: "https://www.linkedin.com/in/yasseralsaied//", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "John D. Babyack", img: "https://www.fiware.org/wp-content/directories/people/images/200px/john-babyack.jpg", position: "Smart Cities Sales Manager", company: "Libelium", "company-link": "https://www.libelium.com/",
    content: "John David has dedicated his career to improving urban life through technology and politics. In his current role at Libelium, John David provides his deep understanding of the public sector and his expertise in IoT technologies and Smart Cities to deliver custom solutions that meet the specific needs of each city, developing important projects in Spanish cities such as Murcia, Bizkaia, Barcelona or La Palma.", linkedin: "https://www.linkedin.com/in/babyack/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Francesco Bonfiglio", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francesco-bonfiglio.jpg", position: "CEO", company: "Gaia-X", "company-link": "https://gaia-x.eu/",
    content: "Francesco Bonfiglio joined GAIA-X in March 2021 as the new CEO. With more than 30 years’ experience in the business of consulting and information technology, Francesco brings his knowledge of the cloud and data market needs, and his vision on how Gaia-X should revolutionize it. Independent Advisor since 2020, he has spent his previous professional life as an executive in many Italian and Multinational contexts. Formerly Chief Executive Officer for ENGINEERING D.HUB (Hybrid Cloud and Digital Transformation company within the largest Italian System Integrator Group), Vice President for Technology Services at AVANADE and Managing Director within the ACCENTURE Group, Chief Technology Officer for HEWLETT-PACKARD EMEA, SW Factory Director at UNISYS, Technical Director and Methodology Evangelist at RATIONAL SOFTWARE amongst his positions.", linkedin: "https://www.linkedin.com/in/francesco-bonfiglio-a068562/", twitter: "https://twitter.com/franzbonf", domain: "", location: "",
    flag: "", },
    { name: "Mads W. Bonne", img: "https://www.fiware.org/wp-content/directories/people/images/200px/mads-w-bonne.jpg", position: "Director of Innovation Strategy", company: "KMD", "company-link": "https://www.kmd.dk/",
    content: "Mads W. Bonne is Director of innovation Strategy and CEO of KMD Venture. For more than 10 years Mads has worked with innovation in the public sector, past 7 years in in KMD an NEC Company. In his role as Director of Innovation Strategy he has been a lead driver for exploring and implementing FIWARE as part of KMD’s offerings and services. He has been leading the user engagement and explored how open standards and open source can accelerate innovation projects and make cities greener and smarter.", linkedin: "https://www.linkedin.com/in/madsbonne/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Flavio Bono", img: "https://www.fiware.org/wp-content/directories/people/images/200px/flavio-bono.jpg", position: "Project Portfolio Leader", company: "JRC – EC", "company-link": "https://joint-research-centre.ec.europa.eu/index_en",
    content: "", linkedin: "https://www.linkedin.com/in/flaviobono/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Cristina Brandtstetter", img: "https://www.fiware.org/wp-content/directories/people/images/200px/cristina-brandtstetter.jpg", position: "Chief Marketing Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Cristina Brandtstetter (f) holds the position of the Chief Marketing Officer (CMO) and is member of the Board of Officers. She has a strong track record of success in the global Manufacturing and Automation Operations and Central European Lifestyle industries, building out strategic and operational capabilities, leading marketing, B2B partner teams, business development and strategic programmes, and cultivating strong thought leader relationships across multiple specialties. Her 25+ years in software, manufacturing and controlling systems include international operations, CEO and CIO roles, marketing and post-merger leadership roles with Siemens and Siemens acquired companies, and many years’ expatriate assignments in Belgium, Italy, the US and the UK. Cristina holds a degree in business administration and currently pursues an MBA programme in Leadership and Management. Her Marketing sweatspots can be found with internal and market communications, brand development and positioning, community building and impact through events, as well as international strategy and business development.", linkedin: "https://www.linkedin.com/in/brandtstetter", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Alex Carrasco", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alex-carrasco.jpg", position: "Head of Communications", company: "ISDI Accelerator", "company-link": "https://accelerator.isdi.education/",
    content: "Over 8 years experience supporting startups worldwide, leading the marketing and communication units for different accelerators and entrepreneurship hubs in Europe. Since 2019, Head of Communications at ISDI Accelerator, managing several European funded programs, Corporate Innovation programs and ISDI’s Own Ventures.", linkedin: "https://www.linkedin.com/in/alex-carrasco-szulc/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Giovanni Coppa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/giovanni-coppa.jpg", position: "Coordinator Astrid iHub", company: "WOBCOM", "company-link": "https://www.wobcom.de/",
    content: "More than 10 years of experience in Data Center and digital transformation. I am passionate about energy efficiency and environmental friendly technologies, with a strong interest in digital revolution and strategic innovation.", linkedin: "https://www.linkedin.com/in/giovannicoppa/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Andrea Cruciani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-cruciani.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "TeamDev", "company-link": "https://www.teamdev.it/en/",
    content: "Andrea is the Agricolus co-founder and CEO, member of FIWARE Foundation BoD, Chairman of the FIWARE Smart AgriFood MSC. He runs the international business area and the financial aspects of the company and he has a technical background and experience in applications Development, Enterprise Architectures, Cloud Computing, and GIS. Andrea is involved in Innovative Startup Evolution and scaleup, during the years he worked with Public Administration, multinational companies, NGOs, and SMEs. He is a speaker for several universities and public events where he is invited to discuss entrepreneurship and digital transformation, and he is a contributor in several technical articles and publications about agritech.", linkedin: "https://www.linkedin.com/in/andreacruciani/", twitter: "https://twitter.com/kokkete", domain: "", location: "",
    flag: "", },
    { name: "Jason Fox", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jason-fox.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Jason Fox (m) has been working for FIWARE Foundation for the last five years in the role of technical evangelist, educating and diseminating information about NGSI interfaces, JSON-LD, Linked Data, the components within the FIWARE Catalogue and Securing FIWARE architectures. Before joining FIWARE, he worked as a software engineer for over 20 years in various roles both in Germany and the United Kingdom using a wide variety of programming languages ranging from C++ to Java to Node.js. This has included coding the software behind selling lottery tickets online for the British National Lottery, and and developing and maintaining technical documentation applications for Nokia.", linkedin: "https://www.linkedin.com/in/jason-fox-8a79563/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Pierre Golz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/pierre-golz.jpg", position: "Chief Digital Officer", company: "City of Herne", "company-link": "https://www.herne.de/",
    content: "After getting his diploma as a public administration specialist, Pierre joined the city as an organizational developer and change manager. Since 2013, he has been working on projects focused on digitization and process management, and, at the age of 31, Pierre is the city’s youngest CDO to date. Pierre is also a lecturer in E-Government, Digitization, and Knowledge Management (among other areas) and feels that being able to combine science, economy and public management adds considerably to his career and role within the city.", linkedin: "https://www.linkedin.com/in/pierre-golz-311396156/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Daniel Gómez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/daniel-gomez.jpg", position: "Researcher", company: "CARTIF", "company-link": "https://www.cartif.es/en/home/",
    content: "", linkedin: "https://www.linkedin.com/in/daniel-g%C3%B3mez-mart%C3%ADn/", twitter: "https://twitter.com/Danigomar", domain: "", location: "",
    flag: "", },
    { name: "Antonio Jara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonio-jara.jpg", position: "Chief Scientific Officer", company: "Libelium", "company-link": "https://www.libelium.com/",
    content: "Antonio has a PhD from the University of Murcia (Spain) and a MBA from the ENAE business school and UCAM (2012). He has received entrepreneurship awards from ENAE, emprendeGo, IPSO Alliance Award for its disruptive innovation in the IoT. As part of HOP Ubiquitous, Jara is focused on the Smart Cities market with solutions for citizens engagements, tourism, active participation, physical web and environmental monitoring (air quality sensors) in projects such as ENIAC SAFESENS, interoperability / pilots (SmartSDK, Synchronicity, Organicity, BeinCPPS) and also in several actions related to security/privacy (INPUT and FORTIKA).", linkedin: "https://www.linkedin.com/in/jara-libelium/", twitter: "https://twitter.com/antonio_jara", domain: "", location: "",
    flag: "", },
    { name: "Ernoe Kovacs", img: "https://www.fiware.org/wp-content/directories/people/images/200px/erno-kovacs.jpg", position: "Senior Manager", company: "NEC Lab Europe", "company-link": "https://www.neclab.eu/",
    content: "Ernö started his journey in the scientific world as a student working for IBM Scientific Center in Heidelberg, Germany, where he got to know more about the research process and how the boundaries of technologies were pushed worldwide. He then moved on to do his PhD at the University of Stuttgart with a long-term collaboration and research visit to HP in Fort Collins, Colorado, USA. Afterward, he joined Sony’s research lab to work on topics such as mobile communication, context-aware services, and broadband multimedia. In the early 2000s, Ernö was leading teams at NEC, establishing context-aware services and IoT as a long term research topic.", linkedin: "https://www.linkedin.com/in/ern%C3%B6-kovacs-1459041/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Oscar Lazaro", img: "https://www.fiware.org/wp-content/directories/people/images/200px/oscar-lazaro.jpg", position: "Managing Director", company: "Innovalia", "company-link": "https://innovalia.org/en/",
    content: "Oscar Lazaro is Director of Innovalia Association and supports innovation transfer towards Innovalia business units. He leads the WEF Advanced Manufacturing HUB (AMHUB) and IDSA Hub in Spain. He is board member of BAIDATA, the Digital Factory Alliance (DFA) among other responsibilities. He has extensive experience in the use of FIWARE for Industry, coordinated the BOOST 4.0 BDVA lighthouse initiative and he now leads the RE4DY follow up project, addressing the fast deployment of Manufacturing Data Networks. His main area of expertise lies in Industry 4.0, AI and data related topics.", linkedin: "https://www.linkedin.com/in/oscar-lazaro-100a3a3/", twitter: "https://twitter.com/olazaro74", domain: "", location: "",
    flag: "", },
    { name: "Franck Le Gall", img: "https://www.fiware.org/wp-content/directories/people/images/200px/franck-le-gall.jpg", position: "Chief Executive Officer", company: "Easy Global Market", "company-link": "https://www.egm.io/en/egm-the-innovation-factory",
    content: "Franck Le Gall is CEO at Easy Global Market, an innovative SME focused on integration and validation of emerging technologies. He is driving company development to deploy IoT and data technologies over vertical markets (water, agriculture, smart territories, environment, etc.). He involves himself in the standardization area including ETSI where he is co-chairman of the ETSI ISG-CIM working group on NGSI-LD. He is also chairing the interfaces working group of the FIWARE Technical Steering Committee (TSC) as well as the joint ETSI-FIWARE Foundation working group on Digital Twins. Finally, he is the Co-chair of the Smart Water working group of the ICT4Water European research cluster. He continuously contributes and drives several projects for public and private customers.", linkedin: "https://www.linkedin.com/in/francklegall/", twitter: "https://twitter.com/franck_le_gall", domain: "", location: "",
    flag: "", },
    { name: "Martino Maggio", img: "https://www.fiware.org/wp-content/directories/people/images/200px/martino-maggio.jpg", position: "Researcher", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Martino Maggio is a senior researcher and project manager. He got his master degree in Computer Science Engineering and, since 2005, he has been working as a researcher in Engineering Ingegneria Informatica R&amp;D laboratory. He is part of the Open Government R&amp;D Group researching in the domain of public service innovation and co-creation, smart city technologies and interoperability. In the last years he has been involved in several European co-funded research projects (inside FP7, CIP PSP ICT and H2020 programme) as technical manager and project coordinator: his expertise is mainly focused on software architecture design, data and platform interoperability, open data and project management (PMP PMI Certified in 2014). Currently he is coordinating INTERSTAT project (CEF Telecom - Public Open Data), that aims at developing a framework to enable interoperability in the field of open statistical data.", linkedin: "https://www.linkedin.com/in/martinomaggio/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Angelo Marguglio", img: "https://www.fiware.org/wp-content/directories/people/images/200px/angelo-marguglio.jpg", position: "Research Area Manager", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Angelo Marguglio is the head of the “Smart Industry and Agrifood” Unit within the Industry and Security Technologies, Research and Innovation (IS3) Lab. Main role as Research Area Manager mainly concerns with coordinating a group of more than 30 researchers using state-of-the-art PM methodologies (e.g. PMP and Agile/SCRUM); defining the strategic roadmap and the operational plans of the Unit; coordinating several research projects and collaborating with the Industry Business Unit of the Engineering Group.", linkedin: "https://www.linkedin.com/in/amarguglio/", twitter: "https://twitter.com/angmarguglio", domain: "", location: "",
    flag: "", },
    { name: "Haydar Mecit", img: "https://www.fiware.org/wp-content/directories/people/images/200px/haydar-mecit.jpg", position: "Full Professor", company: "Hochschule Bochum", "company-link": "https://www.hochschule-bochum.de/",
    content: "Haydar was appointed to Bochum University of Applied Sciences in 2019 as part of an endowed professorship by the local utility Stadtwerke Herne AG. In the Department of Electrical Engineering and Computer Science his research area Urban Energy and Mobility Systems deals with R&amp;D on smart city solutions. His research focuses on the integration of IoT sensor technologies and IT platforms in real-world laboratories in urban areas whereas application areas are related to smart energy, environment and mobility. Previously, Haydar worked as a senior expert in a central R&amp;D department of the utility innogy SE, now a division of E.ON SE on topics related to electric mobility and data driven business models. Between 2005 and 2017 he worked in various business areas of the technology company thyssenkrupp AG, most recently as a senior engineer R&amp;D in an innovation department in the areas of mobility, energy and infrastructure. In addition, he is also a member of the FIWARE Foundation’s Smart Energy Mission Support Committee.", linkedin: "https://www.linkedin.com/in/haydarmecit/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Xhulja Melyshi", img: "https://www.fiware.org/wp-content/directories/people/images/200px/xhulja-melyshi.jpg", position: "Marketplace Manager", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "", linkedin: "https://www.linkedin.com/in/xhulja-melyshi-273b66211/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Nejib Moalla", img: "https://www.fiware.org/wp-content/directories/people/images/200px/nejib-moalla.jpg", position: "Full Professor", company: "Université Lumière Lyon 2", "company-link": "https://welcome.univ-lyon2.fr/",
    content: "Prof. Nejib Moalla, received a master degree in Computer Science. He finished his Ph.D. thesis in 2007 and hisnhabilitation in 2015. He held the responsibility of the project management department between 2008 and 2012. His research activities deal with software and data engineering to support digital transformation with finalised solutionsin Manufacturing, Healthcare, Smart Farming, etc. In software engineering, the developed research concepts and solutions cover: software quality, service-oriented architectures, microservice architecture, performance-based service reuse, service personalisation, ontology engineering, knowledge management, decision support, etc. In data engineering, the research activities cover: the application of data-driven artificial intelligence technics (Machine Learning, etc.) to support decision-making processes in a digital twin perspective. Nejib Moalla is in charge of the DIH ICT4Manuf. As a project manager, he coordinates regional industrial projects and continues to be involved in different collaborative and international projects: H2020 DIH4CPS (2020-2022), EPlus ENHANCE (2021-2024, Coordinator), EPlus TETRIS (2021-2024), H2020 vf-OS (2017-2019), FIPPP FP7 FITMAN (2013-2015), etc. He is a member of several international program committees (IPC) of international journals and conferences.", linkedin: "https://www.linkedin.com/in/n%C3%A9jib-moalla-7b846513/", twitter: "https://twitter.com/nejib_moalla", domain: "", location: "",
    flag: "", },
    { name: "Luis Muñoz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/luis-munoz.jpg", position: "Full Professor", company: "University of Cantabria", "company-link": "https://web.unican.es/en/Pages/default.aspx",
    content: "Prof. Luis Muñoz received both the Telecommunications Engineering degree and Ph.D. from the Polytechnical University of Cataluña (UPC), Spain. He also holds a Master in Mathematics, Statistic and Operation Research (Licenciado en Ciencias Matemáticas, UNED). His research focuses on advanced data transmission techniques, heterogeneous wireless multihop networks, Internet o Things, technologies and services in the context of smart cities and applied mathematical methods for telecommunications. He has participated in several National and European research projects belonging to the 4th, 5th, 6th and 7th and H2020 Framework Program in which he was technical manager of SmartSantander. He has published over 150 journal and conference papers. He serves as editor of several journals and he has been invited to participate in the Steering Committee and Technical Program Committee of the most relevant international conferences. In parallel to this activity, he serves as consultant for the Spanish Government as well as for different companies in Europe. Last but not least, he has served as an expert of the ETSI and European Commission.", linkedin: "", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Francesco Mureddu", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francesco-mureddu.jpg", position: "Director", company: "The Lisbon Council", "company-link": "https://lisboncouncil.net/",
    content: "", linkedin: "https://www.linkedin.com/in/francescomureddu/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Lars Nagel", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lars-nagel.jpg", position: "CEO", company: "IDSA", "company-link": "https://internationaldataspaces.org/",
    content: "Lars Nagel is CEO of the International Data Spaces Association since it’s foundation in 2016. He is also a member of the Executive Board of Digital Hub Management GmbH, where he manages innovation and technology transfer. Previously, Lars founded and led GlobalGate, a provider of learning environments for industrial and research institutions. Lars studied mechanical engineering at the Technical University of Dortmund and graduated with a diploma in engineering.", linkedin: "https://www.linkedin.com/in/lars-nagel-704411b8/", twitter: "https://twitter.com/larsmnagel", domain: "", location: "",
    flag: "", },
    { name: "Boris Otto", img: "https://www.fiware.org/wp-content/directories/people/images/200px/boris-otto.jpg", position: "Executive Director", company: "Fraunhofer ISST", "company-link": "https://www.isst.fraunhofer.de/",
    content: "", linkedin: "https://www.linkedin.com/in/boris-otto-5701b51", twitter: "https://twitter.com/drborisotto", domain: "", location: "",
    flag: "", },
    { name: "Sophie Proust", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sophie-proust.jpg", position: "CTO", company: "Atos", "company-link": "https://atos.net/en/",
    content: "", linkedin: "https://www.linkedin.com/in/sophie-proust/", twitter: "https://twitter.com/so_proust", domain: "", location: "",
    flag: "", },
    { name: "Jonathan Reichental", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jonathan-reichental.jpg", position: "Founder", company: "Human Future", "company-link": "http://www.humanfuture.io/",
    content: "", linkedin: "https://www.linkedin.com/in/reichental/", twitter: "https://twitter.com/reichental", domain: "", location: "",
    flag: "", },
    { name: "Joaquín Salvachúa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/joaquin-salvachua.jpg", position: "Associate Professor", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "Prof. Joaquín Salvachúa received a master degree in Computer Science. He holds the Orange Chair for the “Science of Complex Networks” and the Kairos Chair on “Bank Middleware and Blockchain” at UPM and is a member of the UPM-ING and CyberAula groups. He has participated in several European research projects with several publications at international magazines, books and conferences. (https://orcid.org/0000-0002-7269-8079). Also have participated in several standardization activities, including been coauthor one RFC ( RFC 8802 ).His research focuses today on WebRTC, Cloud infrastructure, social graphs and recommendation, agile cloud infrastructures, P2P, DHT (Distributed HashTables), IOT, Non SQL Data Bases, Big data processing architectures, Identity Management and BlockChain distributed agreement algorithms.His teaching duties includes cloud computing, distributed application development, Databases, Web Full-stack development, Blockchain architecture, Data Engineering and Big data architecture and applications. Has been involved in the FIWARE Initiative since it started (2010) and he is architect and developer of several GE related to security, data persistence and Big Data analysis.", linkedin: "https://es.linkedin.com/in/jsalvachua", twitter: "https://twitter.com/jsalvachua", domain: "", location: "",
    flag: "", },
    { name: "David Seoane", img: "https://www.fiware.org/wp-content/directories/people/images/200px/david-seoane.jpg", position: "Head of Communities", company: "FundingBox", "company-link": "https://fundingbox.com/",
    content: "Over 12 years of experience in Fundraising in EU programs, Since, 2020, responsible for the Community Building Strategy across all European and private projects managed by FundingBox, curating the FundingBox Spaces database (+45k users).", linkedin: "https://www.linkedin.com/in/davidseoane/", twitter: "https://twitter.com/davidseoanevila", domain: "", location: "",
    flag: "", },
    { name: "Harald Sundmaeker", img: "https://www.fiware.org/wp-content/directories/people/images/200px/harald-sundmaeker.jpg", position: "Senior Researcher", company: "ATB Bremen", "company-link": "https://www.atb-bremen.de/",
    content: "Senior Researcher at ATB-Bremen, and vice-chair of the FIWARE SmartAgriFood Mission Support Committee, Harold has been working in European research and innovation projects in different business domains for the past 20 years. Harald joined FIWARE’s journey from its beginning, co-leading/coordinating agri-food-related innovation projects (i.e. SmartAgriFood, FIspace &amp; FInish) and working in the large scale projects IoF2020 and SmartAgriHubs as work package leader. Harald is addressing challenges from farm to fork, specifically aiming at the realization of new ways of work and collaboration. Currently, he is addressing topics like service monetization, interoperability and data model development.", linkedin: "https://www.linkedin.com/in/sundmaeker", twitter: "https://twitter.com/HSundmaeker", domain: "", location: "",
    flag: "", },
    { name: "Georg Thallinger", img: "https://www.fiware.org/wp-content/directories/people/images/200px/georg-thallinger.jpg", position: "Research Manager", company: "Joanneum Research", "company-link": "https://www.joanneum.at/en/",
    content: "Georg works since 1992 with JOANNEUM RESEARCH, DIGITAL - Institute of Digital Technologies. He is responsible for the implementation of innovative solutions in the areas of content based analysis and retrieval of audiovisual media, media monitoring, traffic telematics and security. He has successfully managed numerous national and international projects in the field (e.g. DIAMANT, FascinatE, ICoSOLE, ATLANTIS, TailoredMedia). Georg is currently the coordinator of the Project DIDYMOS-XR creating automatic algorithms to keep Digital Twins in sync with the real world.", linkedin: "https://www.linkedin.com/in/georgthallinger", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Florian Tursky", img: "https://www.fiware.org/wp-content/directories/people/images/200px/florian-tursky.jpg", position: "State Secretary", company: "Austrian Ministry of Finance", "company-link": "https://www.bmf.gv.at/en.html",
    content: "", linkedin: "https://www.linkedin.com/in/florian-tursky-86063592/", twitter: "https://twitter.com/ftursky", domain: "", location: "",
    flag: "", },
    { name: "Margherita Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/margherita-volpe.jpg", position: "R&amp;I Consultant", company: "Zabala", "company-link": "https://www.zabala.eu/",
    content: "", linkedin: "https://www.linkedin.com/in/margherita-volpe-60020235/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Gaetano Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gaetano-volpe.jpg", position: "CEO", company: "Latitudo 40", "company-link": "https://www.latitudo40.com/",
    content: "Gaetano is the CEO of Latitudo 40, a startup that uses satellite data to improve life on our planet. After working for over 20 years in space-related companies, launching new products and services based on the integration of IT with space technologies (telecommunications, navigation and remote sensing), he decided to combine his passion for space technologies with the need to improve the environmental impact of our cities. For Gaetano, innovation means finding a new solution to a global market problem.", linkedin: "https://www.linkedin.com/in/gaetanovolpe", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Dennis Wendland", img: "https://www.fiware.org/wp-content/directories/people/images/200px/dennis-wendland.jpg", position: "Technical Lead &amp; Architect", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Dennis Wendland (m) is a Technical Lead and Architect at the FIWARE Foundation where he is involved in a variety of projects in the field of data spaces. He holds a doctorate in high energy physics from Humboldt University of Berlin gaining a broad experience in the development of particle collision data analysis software and the statistical analysis of large data sets. His doctoral dissertation was about the search of new elementary particles at high-energy collisions at the CERN Large Hadron Collider in Geneva. After his doctorate, he has also worked at T-Systems and Deutsche Telekom AG acquiring expertise in the development, architecture and management of large software projects.", linkedin: "https://www.linkedin.com/in/dennis-wendland/", twitter: "", domain: "", location: "",
    flag: "", },
];