var companies = [
        'Atos',
        'Austrian Ministry of Finance',
        'AWS',
        'City of Herne',
        'Engineering',
        'FIWARE Foundation',
        'Fraunhofer ISST',
        'FundingBox',
        'Gaia-X',
        'Hochschule Bochum',
        'Human Future',
        'IDSA',
        'Innovalia',
        'ISDI Accelerator',
        'JRC – EC',
        'Latitudo 40',
        'NEC Lab Europe',
        'WOBCOM',
        'Zabala',
]; var departments = [
]; var domains = [
]; var titles = [
        'CDO',
        'CEO',
        'CMO',
        'Consultant',
        'Coordinator',
        'CTO',
        'Data Modeling Expert',
        'Director',
        'Evangelist',
        'Founder',
        'Full Professor',
        'Head of Communications',
        'Head of Communities',
        'Head of IoT',
        'Manager',
        'Managing Director',
        'Marketplace Manager',
        'Project Portfolio Leader',
        'R&amp;D Manager',
        'Researcher',
        'State Secretary',
        'Technical Expert',
        'VP',
]; var countries = [
]; var modalData = [
    { name: "Alberto Abella", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alberto-abella.jpg", position: "Data Modeling Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Alberto Abella (m) is PhD in Business (Open data) and Telecommunications Engineer and Master in Total Quality Management, Business Administration and Business Organization. He works as a Data Modelling Expert and Technical Evangelist at FIWARE and currently is the responsible person for the smart data models initiative.", linkedin: "https://www.linkedin.com/in/albertoabella/", twitter: "https://twitter.com/aabella", domain: "", location: "",
    flag: "", },
    { name: "Ulrich Ahle", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ulrich-ahle.jpg", position: "Chief Executive Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Ulrich Ahle (m) is a reputed executive in the industrial sector, formerly Vice President and leader of Manufacturing, Retail &amp; Transportation business and responsible for Industry 4.0 at Atos in Germany. He is also founder and member of the Board of the International Data Spaces Association in Germany and served 16 years in the Board of prostep ivip, until April 2018. After an apprenticeship as toolmaker at Hella KG, he studied Mechanical Engineering at the University of Paderborn. In his career, Ulrich held several positions as development engineer, Director of PLM services, Sales Director and Vice President. He has been part of Nixdorf Computer AG, Siemens and Atos. Since January 2017, Ulrich acts as Chief Executive Officer of FIWARE Foundation.", linkedin: "https://de.linkedin.com/in/ahlefiware", twitter: "https://twitter.com/UlrichAhle", domain: "", location: "",
    flag: "", },
    { name: "Yasser Alsaied", img: "https://www.fiware.org/wp-content/directories/people/images/200px/yasser-alsaied.jpg", position: "VP &amp; Head of AWS IoT", company: "AWS", "company-link": "https://aws.amazon.com/",
    content: "", linkedin: "https://www.linkedin.com/in/yasseralsaied//", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Francesco Bonfiglio", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francesco-bonfiglio.jpg", position: "CEO", company: "Gaia-X", "company-link": "https://gaia-x.eu/",
    content: "Francesco Bonfiglio joined GAIA-X in March 2021 as the new CEO. With more than 30 years’ experience in the business of consulting and information technology, Francesco brings his knowledge of the cloud and data market needs, and his vision on how Gaia-X should revolutionize it. Independent Advisor since 2020, he has spent his previous professional life as an executive in many Italian and Multinational contexts. Formerly Chief Executive Officer for ENGINEERING D.HUB (Hybrid Cloud and Digital Transformation company within the largest Italian System Integrator Group), Vice President for Technology Services at AVANADE and Managing Director within the ACCENTURE Group, Chief Technology Officer for HEWLETT-PACKARD EMEA, SW Factory Director at UNISYS, Technical Director and Methodology Evangelist at RATIONAL SOFTWARE amongst his positions.", linkedin: "https://www.linkedin.com/in/francesco-bonfiglio-a068562/", twitter: "https://twitter.com/franzbonf", domain: "", location: "",
    flag: "", },
    { name: "Flavio Bono", img: "https://www.fiware.org/wp-content/directories/people/images/200px/flavio-bono.jpg", position: "Project Portfolio Leader", company: "JRC – EC", "company-link": "https://joint-research-centre.ec.europa.eu/index_en",
    content: "", linkedin: "https://www.linkedin.com/in/flaviobono/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Cristina Brandtstetter", img: "https://www.fiware.org/wp-content/directories/people/images/200px/cristina-brandtstetter.jpg", position: "Chief Marketing Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Cristina Brandtstetter (f) holds the position of the Chief Marketing Officer (CMO) and is member of the Board of Officers. She has a strong track record of success in the global Manufacturing and Automation Operations and Central European Lifestyle industries, building out strategic and operational capabilities, leading marketing, B2B partner teams, business development and strategic programmes, and cultivating strong thought leader relationships across multiple specialties. Her 25+ years in software, manufacturing and controlling systems include international operations, CEO and CIO roles, marketing and post-merger leadership roles with Siemens and Siemens acquired companies, and many years’ expatriate assignments in Belgium, Italy, the US and the UK. Cristina holds a degree in business administration and currently pursues an MBA programme in Leadership and Management. Her Marketing sweatspots can be found with internal and market communications, brand development and positioning, community building and impact through events, as well as international strategy and business development.", linkedin: "https://www.linkedin.com/in/brandtstetter", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Alex Carrasco", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alex-carrasco.jpg", position: "Head of Communications", company: "ISDI Accelerator", "company-link": "https://accelerator.isdi.education/",
    content: "Over 8 years experience supporting startups worldwide, leading the marketing and communication units for different accelerators and entrepreneurship hubs in Europe. Since 2019, Head of Communications at ISDI Accelerator, managing several European funded programs, Corporate Innovation programs and ISDI’s Own Ventures.", linkedin: "https://www.linkedin.com/in/alex-carrasco-szulc/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Giovanni Coppa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/giovanni-coppa.jpg", position: "Coordinator Astrid iHub", company: "WOBCOM", "company-link": "https://www.wobcom.de/",
    content: "More than 10 years of experience in Data Center and digital transformation. I am passionate about energy efficiency and environmental friendly technologies, with a strong interest in digital revolution and strategic innovation.", linkedin: "https://www.linkedin.com/in/giovannicoppa/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Jason Fox", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jason-fox.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Jason Fox (m) has been working for FIWARE Foundation for the last five years in the role of technical evangelist, educating and diseminating information about NGSI interfaces, JSON-LD, Linked Data, the components within the FIWARE Catalogue and Securing FIWARE architectures. Before joining FIWARE, he worked as a software engineer for over 20 years in various roles both in Germany and the United Kingdom using a wide variety of programming languages ranging from C++ to Java to Node.js. This has included coding the software behind selling lottery tickets online for the British National Lottery, and and developing and maintaining technical documentation applications for Nokia.", linkedin: "https://www.linkedin.com/in/jason-fox-8a79563/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Pierre Golz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/pierre-golz.jpg", position: "Chief Digital Officer", company: "City of Herne", "company-link": "https://www.herne.de/",
    content: "After getting his diploma as a public administration specialist, Pierre joined the city as an organizational developer and change manager. Since 2013, he has been working on projects focused on digitization and process management, and, at the age of 31, Pierre is the city’s youngest CDO to date. Pierre is also a lecturer in E-Government, Digitization, and Knowledge Management (among other areas) and feels that being able to combine science, economy and public management adds considerably to his career and role within the city.", linkedin: "https://www.linkedin.com/in/pierre-golz-311396156/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Ernoe Kovacs", img: "https://www.fiware.org/wp-content/directories/people/images/200px/erno-kovacs.jpg", position: "Senior Manager", company: "NEC Lab Europe", "company-link": "https://www.neclab.eu/",
    content: "Ernö started his journey in the scientific world as a student working for IBM Scientific Center in Heidelberg, Germany, where he got to know more about the research process and how the boundaries of technologies were pushed worldwide. He then moved on to do his PhD at the University of Stuttgart with a long-term collaboration and research visit to HP in Fort Collins, Colorado, USA. Afterward, he joined Sony’s research lab to work on topics such as mobile communication, context-aware services, and broadband multimedia. In the early 2000s, Ernö was leading teams at NEC, establishing context-aware services and IoT as a long term research topic.", linkedin: "https://www.linkedin.com/in/ern%C3%B6-kovacs-1459041/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Oscar Lazaro", img: "https://www.fiware.org/wp-content/directories/people/images/200px/oscar-lazaro.jpg", position: "Managing Director", company: "Innovalia", "company-link": "https://innovalia.org/en/",
    content: "Oscar Lazaro is Director of Innovalia Association and supports innovation transfer towards Innovalia business units. He leads the WEF Advanced Manufacturing HUB (AMHUB) and IDSA Hub in Spain. He is board member of BAIDATA, the Digital Factory Alliance (DFA) among other responsibilities. He has extensive experience in the use of FIWARE for Industry, coordinated the BOOST 4.0 BDVA lighthouse initiative and he now leads the RE4DY follow up project, addressing the fast deployment of Manufacturing Data Networks. His main area of expertise lies in Industry 4.0, AI and data related topics.", linkedin: "https://www.linkedin.com/in/oscar-lazaro-100a3a3/", twitter: "https://twitter.com/olazaro74", domain: "", location: "",
    flag: "", },
    { name: "Martino Maggio", img: "https://www.fiware.org/wp-content/directories/people/images/200px/martino-maggio.jpg", position: "Researcher", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Martino Maggio is a senior researcher and project manager. He got his master degree in Computer Science Engineering and, since 2005, he has been working as a researcher in Engineering Ingegneria Informatica R&amp;D laboratory. He is part of the Open Government R&amp;D Group researching in the domain of public service innovation and co-creation, smart city technologies and interoperability. In the last years he has been involved in several European co-funded research projects (inside FP7, CIP PSP ICT and H2020 programme) as technical manager and project coordinator: his expertise is mainly focused on software architecture design, data and platform interoperability, open data and project management (PMP PMI Certified in 2014). Currently he is coordinating INTERSTAT project (CEF Telecom - Public Open Data), that aims at developing a framework to enable interoperability in the field of open statistical data.", linkedin: "https://www.linkedin.com/in/martinomaggio/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Angelo Marguglio", img: "https://www.fiware.org/wp-content/directories/people/images/200px/angelo-marguglio.jpg", position: "Research Area Manager", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Angelo Marguglio is the head of the “Smart Industry and Agrifood” Unit within the Industry and Security Technologies, Research and Innovation (IS3) Lab. Main role as Research Area Manager mainly concerns with coordinating a group of more than 30 researchers using state-of-the-art PM methodologies (e.g. PMP and Agile/SCRUM); defining the strategic roadmap and the operational plans of the Unit; coordinating several research projects and collaborating with the Industry Business Unit of the Engineering Group.", linkedin: "https://www.linkedin.com/in/amarguglio/", twitter: "https://twitter.com/angmarguglio", domain: "", location: "",
    flag: "", },
    { name: "Haydar Mecit", img: "https://www.fiware.org/wp-content/directories/people/images/200px/haydar-mecit.jpg", position: "Full Professor", company: "Hochschule Bochum", "company-link": "https://www.hochschule-bochum.de/",
    content: "Haydar was appointed to Bochum University of Applied Sciences in 2019 as part of an endowed professorship by the local utility Stadtwerke Herne AG. In the Department of Electrical Engineering and Computer Science his research area Urban Energy and Mobility Systems deals with R&amp;D on smart city solutions. His research focuses on the integration of IoT sensor technologies and IT platforms in real-world laboratories in urban areas whereas application areas are related to smart energy, environment and mobility. Previously, Haydar worked as a senior expert in a central R&amp;D department of the utility innogy SE, now a division of E.ON SE on topics related to electric mobility and data driven business models. Between 2005 and 2017 he worked in various business areas of the technology company thyssenkrupp AG, most recently as a senior engineer R&amp;D in an innovation department in the areas of mobility, energy and infrastructure. In addition, he is also a member of the FIWARE Foundation’s Smart Energy Mission Support Committee.", linkedin: "https://www.linkedin.com/in/haydarmecit/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Xhulja Melyshi", img: "https://www.fiware.org/wp-content/directories/people/images/200px/xhulja-melyshi.jpg", position: "Marketplace Manager", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "", linkedin: "https://www.linkedin.com/in/xhulja-melyshi-273b66211/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Lars Nagel", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lars-nagel.jpg", position: "CEO", company: "IDSA", "company-link": "https://internationaldataspaces.org/",
    content: "Lars Nagel is CEO of the International Data Spaces Association since it’s foundation in 2016. He is also a member of the Executive Board of Digital Hub Management GmbH, where he manages innovation and technology transfer. Previously, Lars founded and led GlobalGate, a provider of learning environments for industrial and research institutions. Lars studied mechanical engineering at the Technical University of Dortmund and graduated with a diploma in engineering.", linkedin: "https://www.linkedin.com/in/lars-nagel-704411b8/", twitter: "https://twitter.com/larsmnagel", domain: "", location: "",
    flag: "", },
    { name: "Boris Otto", img: "https://www.fiware.org/wp-content/directories/people/images/200px/boris-otto.jpg", position: "Executive Director", company: "Fraunhofer ISST", "company-link": "https://www.isst.fraunhofer.de/",
    content: "", linkedin: "https://www.linkedin.com/in/boris-otto-5701b51", twitter: "https://twitter.com/drborisotto", domain: "", location: "",
    flag: "", },
    { name: "Sophie Proust", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sophie-proust.jpg", position: "CTO", company: "Atos", "company-link": "https://atos.net/en/",
    content: "", linkedin: "https://www.linkedin.com/in/sophie-proust/", twitter: "https://twitter.com/so_proust", domain: "", location: "",
    flag: "", },
    { name: "Jonathan Reichental", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jonathan-reichental.jpg", position: "Founder", company: "Human Future", "company-link": "http://www.humanfuture.io/",
    content: "", linkedin: "https://www.linkedin.com/in/reichental/", twitter: "https://twitter.com/reichental", domain: "", location: "",
    flag: "", },
    { name: "David Seoane", img: "https://www.fiware.org/wp-content/directories/people/images/200px/david-seoane.jpg", position: "Head of Communities", company: "FundingBox", "company-link": "https://fundingbox.com/",
    content: "Over 12 years of experience in Fundraising in EU programs, Since, 2020, responsible for the Community Building Strategy across all European and private projects managed by FundingBox, curating the FundingBox Spaces database (+45k users).", linkedin: "https://www.linkedin.com/in/davidseoane/", twitter: "https://twitter.com/davidseoanevila", domain: "", location: "",
    flag: "", },
    { name: "Florian Tursky", img: "https://www.fiware.org/wp-content/directories/people/images/200px/florian-tursky.jpg", position: "State Secretary", company: "Austrian Ministry of Finance", "company-link": "https://www.bmf.gv.at/en.html",
    content: "", linkedin: "https://www.linkedin.com/in/florian-tursky-86063592/", twitter: "https://twitter.com/ftursky", domain: "", location: "",
    flag: "", },
    { name: "Margherita Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/margherita-volpe.jpg", position: "R&amp;I Consultant", company: "Zabala", "company-link": "https://www.zabala.eu/",
    content: "", linkedin: "https://www.linkedin.com/in/margherita-volpe-60020235/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Gaetano Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gaetano-volpe.jpg", position: "CEO", company: "Latitudo 40", "company-link": "https://www.latitudo40.com/",
    content: "Gaetano is the CEO of Latitudo 40, a startup that uses satellite data to improve life on our planet. After working for over 20 years in space-related companies, launching new products and services based on the integration of IT with space technologies (telecommunications, navigation and remote sensing), he decided to combine his passion for space technologies with the need to improve the environmental impact of our cities. For Gaetano, innovation means finding a new solution to a global market problem.", linkedin: "https://www.linkedin.com/in/gaetanovolpe", twitter: "", domain: "", location: "",
    flag: "", },
];