var companies = [];
var departments = [];
var titles = [
        'Closed',
]; var domains = [
        'Academia',
        'Any Legal Entity',
        'Artists',
        'DIHs',
        'Individuals',
        'Integrators',
        'Mid-Caps',
        'NGO',
        'No profit',
        'NPO',
        'Public Entities',
        'Public entities',
        'R&amp;D projects',
        'Research Centers (Third parties)',
        'Research Organisations',
        'RTO',
        'RTOs',
        'Scaleups',
        'SME',
        'SMEs',
        'SMEs Consortium',
        'SMEs Micro Consortium',
        'Startups',
        'Tech Suppliers',
]; var countries = []; 
