var companies = [
        'Iot Global Network',
        'Iot Now',
        'Latitudo 40',
        'Meaningfy',
        'SenLab',
        'Smart Cities World',
        'UM6P',
]; var departments = [
]; var domains = [
]; var titles = [
        'Hosting Partner',
        'Media Partner',
        'Sponsor',
]; var countries = [
]; var modalData = [
    { name: "UM6P", img: "https://www.fiware.org/fiware-summit/rabat-2025/assets/images/logo-um6p.png", "company-link": "https://um6p.ma/en", content: "", linkedin: "https://www.linkedin.com/school/um6p/", twitter: "", type: "Hosting Partner" },
    { name: "Latitudo 40", img: "https://www.fiware.org/fiware-summit/naples-2024/images/sponsors/logo-latitudo40.png", "company-link": "https://latitudo40.com/", content: "&lt;p&gt;Latitudo 40, a Techstars Portfolio Company, is an innovative start-up company that combines the skills and expertise of a large company with the passion and ability to innovate a user-centered design lean organization. Enhancing the 20 years of experience of its founders in ICT, Latitudo 40 has created the easiest and fastest platform to turn satellite imagery into geospatial information to support everyday decisions. For the first time in one platform all the features to automatically search, process and elaborate the images produced by Earth observation satellites and transform them into information to simplify business processes with powerful artificial intelligence and machine learning algorithms.&lt;/p&gt;", linkedin: "https://www.linkedin.com/company/latitudo-40/", twitter: "", type: "Sponsor" },
    { name: "Meaningfy", img: "https://www.fiware.org/fiware-summit/rabat-2025/assets/images/logo-meaningfy.png", "company-link": "https://meaningfy.ws/", content: "&lt;p&gt;Meaningfy designs language solutions that bridge human intuition with machine precision, developing interoperability and data harmonisation systems for European Institutions. Aligned with EU priorities, Meaningfy delivers tangible outcomes that enhance efficiency, transparency, and connectivity in the public sector through services like IT business consulting, architecture development, semantic data strategy, enterprise knowledge graphs, and NLP technology deployment.&lt;/p&gt;", linkedin: "https://www.linkedin.com/company/meaningfy-ws/", twitter: "", type: "Sponsor" },
    { name: "SenLab", img: "https://www.fiware.org/wp-content/directories/organisations/images/senlab.png", "company-link": "https://senlab.io/", content: "&lt;p&gt;SenLab is a leader in pioneering IoT solutions that empower businesses with smarter, more efficient, and secure digital tools. From IoTool (for seamless IoT device management) to IoChat (a private, secure instant messenger), and SandBox (the Swiss Army knife for OT and IT engineers) — SenLab continues to redefine the mobile enterprise space.Through their innovation and technical excellence, they help clients maximize mobile capabilities while reducing reliance on bulky and costly monitoring systems. Their work supports open, trusted, and interoperable digital transformation — core values shared with FIWARE.&lt;/p&gt;", linkedin: "https://www.linkedin.com/company/senlab/", twitter: "", type: "Sponsor" },
    { name: "Iot Global Network", img: "https://www.fiware.org/fiware-summit/naples-2024/images/partners/logo-IoTGN.png", "company-link": "https://www.iotglobalnetwork.com/", content: "&lt;p&gt;IoT Global Network is the ultimate intelligence platform for the IoT industry. IoT Global Network serves as an invaluable source of information for IoT decision makers in all areas of industry and public services, including consumer-related, energy, financial, industrial, healthcare, security and transportation, – and anyone else who would like to learn more about how the Internet of Things will shape tomorrow’s society.&lt;/p&gt;", linkedin: "https://www.linkedin.com/company/iot-global-network/", twitter: "", type: "Media Partner" },
    { name: "Iot Now", img: "https://www.fiware.org/fiware-summit/naples-2024/images/partners/logo-IoTNow.png", "company-link": "www.iot-now.com", content: "&lt;p&gt;With exclusive analyst reports and specialist journalists, IoT Now is the leading global brand covering the Internet of Things, machine-to-machine communications (M2M), embedded devices and connected consumer devices. Delivering webinars, quarterly magazines, white-papers, daily news and expert opinion pieces and podcasts, IoT Now focuses on the deployment of these technologies across the enterprise, automotive, logistics, healthcare, utilities, travel, security and smart city verticals.&lt;/p&gt;", linkedin: "https://www.linkedin.com/company/iot-now/", twitter: "", type: "Media Partner" },
    { name: "Smart Cities World", img: "https://www.fiware.org/fiware-summit/naples-2024/images/partners/logo-smart-cities-world.png", "company-link": "https://www.smartcitiesworld.net/", content: "&lt;p&gt;SmartCitiesWorld is a world-leading platform for sharing ideas and case studies to solve urban challenges that enable us to live in more resilient, sustainable, safe, and prosperous environments.&lt;/p&gt;", linkedin: "https://www.linkedin.com/company/smartcitiesworld/", twitter: "", type: "Media Partner" },
];
