var tracks = [
        'Building collaborative business strategies',
        'Empowering co-creation of tech solutions',
        'Grand Opening',
        'Hands-On Use Cases',
        'Innovation with FIWARE',
        'Tech &amp; Trends',
        'Tech Training',
];
var summitDates = [
        '18-september',
        '19-september',
];
var sessions = [
        'Boosting the co-creation in across the domains',
        'Building more secure and resilient solutions',
        'Data Space Technology',
        'Digital Twins',
        'FISAB &amp; Universities',
        'FIWARE Catalog Components',
        'FIWARE catalog components',
        'Innovation projects on data interoperability',
        'Innovation projects on data platforms and Data Spaces',
        'Innovation projects on green and industry digital twins',
        'NGSI-LD Basics',
        'Security and Deployments',
        'Smart Communities &amp; Mobility',
        'Smart Energy',
        'Technology Vision',
        'The Smart Data Models initiative',
]; 
var speakers = [
        'Abdulrahman Ibrahim',
        'Alberto Abella',
        'Alessandro Spigaroli',
        'Ana Garcia Robles',
        'Andrea Battaglia',
        'Andrea Maioli',
        'Angelo Giuliana',
        'Antonella Longo',
        'Antonello Monti',
        'Antonio Filograna',
        'Antonio Jara',
        'Antonio Skarmeta',
        'Björn Schwarze',
        'Carmen Polcaro',
        'Dasha Davies',
        'Davor Meersman',
        'Eugenia Kovatcheva',
        'Francesco Mureddu',
        'Franck Le Gall',
        'Gaetano Volpe',
        'Gerard van der Hoeven',
        'Gilsoni Lunardi Albino',
        'Giovanni Vaglica',
        'Iffat Tariq',
        'Ilaria Bortone',
        'Jason Fox',
        'Jessica Ocampos',
        'Jesús Ruiz Martinez',
        'Joan Antonio Bernejo',
        'Joaquín Salvachúa',
        'Jorge Hernandez',
        'Jose Benítez',
        'José Ignacio Carretero',
        'Juanjo Hierro',
        'Lars Nagel',
        'Laura Ileana Schipani',
        'Lee Hung-hoon',
        'Luca Remotti',
        'Luigi Coppolino',
        'Luis Muñoz',
        'Luka Keserič',
        'Mannix Manglani',
        'Marco Schuldt',
        'Margherita Volpe',
        'Martin Bauer',
        'Matteo Repetto',
        'Matthias Rehfeld',
        'Mireya de Diego',
        'Nejib Moalla',
        'Pierryl Massal',
        'Raza Jafri',
        'Roberto Di Bernardo',
        'Rocío Díaz Pereira',
        'Satish Jamadagni',
        'Sebastian Blechmann',
        'Sophie Meszaros',
        'Stefano De Panfilis',
        'Thimo Thoeye',
        'Tomohiro Kuwahara',
        'Ulrich Ahle',
        'Vincent Demortier',
        'Yasunori Mochizuki',
        'Yuzhen Li',
]; 
var modalData = {
    "andrea-battaglia":
        { name: "Andrea Battaglia", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-battaglia.jpg", position: "Chief Executive Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "With 20 years of expertise in the Global IT industry, Andrea Battaglia (m) is an accomplished thought leader with a proven track record in Digital Transformation, Enterprise IoT, and Ecosystem development. Thanks to his deep knowledge of the enterprise open-source industry&#x27;s business and technical aspects, Andrea brings a wealth of experience to the forefront of FIWARE&#x27;s mission to empower organizations through innovative open-source technologies, Ecosystem collaboration, and customer-centric vision.", linkedin: "https://www.linkedin.com/in/abattagl/", twitter: "", domain: "", location: "",
        flag: "", },
    "stefano-de-panfilis":
        { name: "Stefano De Panfilis", img: "https://www.fiware.org/wp-content/directories/people/images/200px/stefano-depanfilis.jpg", position: "Chief Operations Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "Stefano de Panfilis (m) is the Chief Operating Officer at FIWARE Foundation. He graduated cum laude in Mathematics at the University of Rome “La Sapienza”. In 1984, he was hired in Engineering Ingegneria Informatica S.P.A as a software engineer. In 1986, he became Project Manager to then move to the R&amp;D department managing the “Formal Methods” unit. In 1993, he supported Engineering to receive the ISO-9001 compliancy. From 1994, he was involved in European R&amp;D. He coordinated SeCSE (IST 6FP), aiming at implement a platform for Service-Centric Systems Engineering, CBSEnet (IST-5FP NoE), CLARiFi (IST 5FP), DOOR (ESPRIT 4FP), SQUAD (INCO-DC), and VALSE (TV&amp;TT) projects, and the ENG- SODEPRO, DECO’ and DOMINARE ESSI Process Improvement Experiments. He also coordinated QualiPSo (IST 6FP) aiming at leverage Open Source Software development to recognised industrial standards, leading a consortium of 20 partners from Europe, Brazil and China. He actively participated to create and set-up the NESSI ETP of which he is the Coordinator of the Strategic Research Agenda Committee. Since 2017, he is employed by FIWARE Foundation as Chief Operations Officer.", linkedin: "https://www.linkedin.com/in/stefano-de-panfilis-1928a11/", twitter: "https://twitter.com/depa01", domain: "", location: "",
        flag: "", },
    "yasunori-mochizuki":
        { name: "Yasunori Mochizuki", img: "https://www.fiware.org/wp-content/directories/people/images/200px/yasunori-mochizuki.jpg", position: "NEC Fellow", company: "NEC Corporation", "company-link": "https://www.nec.com/",
        content: "Yasunori joined NEC in 1987, straight after concluding his PhD in Electronics Engineering. He went on to spend over two decades at NEC’s corporate R&amp;D center, first as a research scientist and later as a department manager, gaining broader technical expertise, including solid-state physics, semiconductor devices/LSIs, and computer science. Later in 2013, Yasunori started working at NEC’s newly-created Business Innovation Unit. As a senior vice president, he was responsible for the corporate-wide technology strategy and IoT business strategy. His current title of NEC Fellow means that he actively participates in innovation policy proposals, global ecosystem building related to smart society, and digital transformation. He is also a BoD member of FIWARE Foundation, World Economic Forum. Fellow, and member of Business at OECD (BIAC) Committee for Digital Economy Policy.", linkedin: "https://www.linkedin.com/in/yasunori-mochizuki-93bab674/", twitter: "https://twitter.com/yasunorimochiz", domain: "", location: "",
        flag: "", },
    "laura-ileana-schipani":
        { name: "Laura Ileana Schipani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/laura-schipani.jpg", position: "Acting CMO", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "With over 23 years of experience, Laura (f) brings a wealth of knowledge in strategic marketing and communications. Her career journey, which began with founding her own fashion brand, has led her through diverse managerial roles across consulting, pharmaceuticals, and ICT industries. She is committed to leveraging her expertise to drive growth, enhance brand distinctiveness, and develop impactful projects that resonate with audiences globally.", linkedin: "https://www.linkedin.com/in/lauraskip/", twitter: "", domain: "", location: "",
        flag: "", },
    "abdulrahman-ibrahim":
        { name: "Abdulrahman Ibrahim", img: "https://www.fiware.org/wp-content/directories/people/images/200px/abdulrahman-ibrahim.jpg", position: "Chief Data and Innovation Officer", company: "MDA", "company-link": "https://www.mda.gov.sa/",
        content: "Mr. Abdulrahman is the Chief Data and Innovation Officer at Madinah Region Development Authority. He is a board member of state-owned Saudi companies. Under his leadership, Madinah was listed in the IMD Smart City Index since 2021. Also, Madinah was accredited by the World Council on City Data as an Early Adopter among the first ten cities worldwide in ISO37122 Smart City Indicators. Before joining the government, he was a Chief Executive Officer in the private sector with 22 years of experience in various industries, such as Consumer Goods, Food Manufacturing, Medical Supplies, and Supply Chain, where his operations covered the GCC market, Levant, and Africa. He’s the co-author of ‘Cities in a Time of Global Emergencies: Can smart cities help?’.", linkedin: "https://www.linkedin.com/in/abdulrahmanibrahim/", twitter: "", domain: "", location: "",
        flag: "", },
    "pierryl-massal":
        { name: "Pierryl Massal", img: "https://www.fiware.org/wp-content/directories/people/images/200px/pierryl-massal.jpg", position: "VP Head of Business development", company: "Atos", "company-link": "https://atos.net/en/",
        content: "Pierryl Massal is Vice President, Head of Global Business development at Atos, a global IT company empowering and driving progress through digital innovation to create a livable and efficient future for the citizens. In this role, Pierryl oversees Atos’ relations and operations especially in the Smart City field enabling Atos to capitalize on opportunities across all industries, including Public Sector, Hospitality, Retail, …. Pierryl has been instrumental in providing central leadership to explore, develop and recommend approaches for sustainable business growth in that domain and manage strategic and brand-promotional partnership opportunities, representation at industry events and government/legislative relations.", linkedin: "https://www.linkedin.com/in/pierryl-massal-8939aa74/", twitter: "https://twitter.com/pierrylmassal", domain: "", location: "",
        flag: "", },
    "jason-fox":
        { name: "Jason Fox", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jason-fox.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "Jason Fox (m) has been working for FIWARE Foundation for the last six years in the role of technical evangelist, educating and diseminating information about NGSI interfaces, JSON-LD, Linked Data, the components within the FIWARE Catalogue and Securing FIWARE architectures. Before joining FIWARE, he worked as a software engineer for over 20 years in various roles both in Germany and the United Kingdom using a wide variety of programming languages ranging from C++ to Java to Node.js. This has included coding the software behind selling lottery tickets online for the British National Lottery, and and developing and maintaining technical documentation applications for Nokia.", linkedin: "https://www.linkedin.com/in/jason-fox-8a79563/", twitter: "", domain: "", location: "",
        flag: "", },
    "alberto-abella":
        { name: "Alberto Abella", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alberto-abella.jpg", position: "Data Modeling Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "Alberto Abella (m) is PhD in Business (Open data) and Telecommunications Engineer and Master in Total Quality Management, Business Administration and Business Organization. He works as a Data Modelling Expert and Technical Evangelist at FIWARE and currently is the responsible person for the smart data models initiative.", linkedin: "https://www.linkedin.com/in/albertoabella/", twitter: "https://twitter.com/aabella", domain: "", location: "",
        flag: "", },
    "juanjo-hierro":
        { name: "Juanjo Hierro", img: "https://www.fiware.org/wp-content/directories/people/images/200px/juanjo-hierro.jpg", position: "Chairman FIWARE TSC", company: "", "company-link": "",
        content: "Juanjo Hierro (m) obtained a degree in Computer Science in 1990 from the Universidad Politecnica de Madrid (UPM) and owns a certificate of research proficiency. In 1990, Juanjo joined Telefónica I+D where he stayed until he joined FIWARE Foundation. During his career at Telefónica, Juanjo had different management responsibilities in the development of mission-critical systems for Telefónica as well as several R&amp;D projects. In April 2011, he became the Chief Architect of the FIWARE programme combining this role with the one of the CTO of the IoT Division at Telefónica R&amp;D since November 2013. Now a days Juanjo is the Chairman of the FIWARE Technical Steering Committee.", linkedin: "https://www.linkedin.com/in/jhierro/", twitter: "https://twitter.com/JuanjoHierro", domain: "", location: "",
        flag: "", },
    "jose-benítez":
        { name: "Jose Benítez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-benitez.jpg", position: "Chief Executive Officer", company: "Secmotic", "company-link": "https://secmotic.com/",
        content: "Since its establishment in 2015, Jose has been at the helm of Secmotic as CEO. His involvement on the Board of Directors of FIWARE since 2017 has contributed to shaping the future of the organization. In 2021, he embarked on a new venture, founding FIWOO Smart Solutions, a company dedicated to delivering FIWARE-based Smart City platform solutions tailored to the needs of the Spanish public sector.", linkedin: "https://www.linkedin.com/in/jose-benitez-secmotic/", twitter: "", domain: "", location: "",
        flag: "", },
    "björn-schwarze":
        { name: "Björn Schwarze", img: "https://www.fiware.org/wp-content/directories/people/images/200px/bjorn-schwarze.jpg", position: "Chief Executive Officer", company: "ADDIX", "company-link": "https://www.addix.net/",
        content: "Björn is a professional experienced business leader. He founded ADDIX GmbH 20 years ago and has turned the company from an ISP into a market leader for WIFI operations and TOP Innovator in the Kiel Region, Germany. Identifying and scoping opportunities, setting up teams and turining ideas into business is key strength. Bringing latest innovations into areas such as smart city, maritime industry and business security is the driving force behind his activities. Since 2022 he is representing the FIWARE Gold Members In Board of Directors of FIWARE.", linkedin: "https://www.linkedin.com/in/bjoernschw/", twitter: "https://twitter.com/Hoernblick", domain: "", location: "",
        flag: "", },
    "margherita-volpe":
        { name: "Margherita Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/margherita-volpe.jpg", position: "Project Manager", company: "Zabala", "company-link": "https://www.zabala.eu/",
        content: "", linkedin: "https://www.linkedin.com/in/margherita-volpe-60020235/", twitter: "", domain: "", location: "",
        flag: "", },
    "gaetano-volpe":
        { name: "Gaetano Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gaetano-volpe.jpg", position: "Chief Executive Officer", company: "Latitudo 40", "company-link": "https://www.latitudo40.com/",
        content: "Gaetano is the CEO of Latitudo 40, a startup that uses satellite data to improve life on our planet. After working for over 20 years in space-related companies, launching new products and services based on the integration of IT with space technologies (telecommunications, navigation and remote sensing), he decided to combine his passion for space technologies with the need to improve the environmental impact of our cities. For Gaetano, innovation means finding a new solution to a global market problem.", linkedin: "https://www.linkedin.com/in/gaetanovolpe", twitter: "", domain: "", location: "",
        flag: "", },
    "mannix-manglani":
        { name: "Mannix Manglani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/mannix-manglani.jpg", position: "Technological Entrepreneur", company: "MNX Online", "company-link": "http://www.mnxonline.com/",
        content: "With a professional career spanning more than 16 years, 12 of them as an entrepreneur, Mannix Manglani is a certified FIWARE Expert who understands the real needs of companies and markets developing useful commercial solutions. He has specialised and has trained others in FIWARE technologies and is focused towards developing and promoting Smart Tourism Destinations models. Currently, while developing the Smart Tourism vertical from the Canary Islands to transform destinations through a more efficient, sustainable and attractive model, he is also: part of the i4Trust experiment of the iGreenPort consortium which promotes a DataSpace related to Smart Ports; Smart digitalisation manager at CleanCarbon Solutions and, FIWARE trainer for University students and future certified Experts.", linkedin: "https://www.linkedin.com/in/mannixmanglani/", twitter: "https://mobile.twitter.com/mnxman", domain: "", location: "",
        flag: "", },
    "vincent-demortier":
        { name: "Vincent Demortier", img: "https://www.fiware.org/wp-content/directories/people/images/200px/vincent-demortier.jpg", position: "President", company: "Faubourg Numérique", "company-link": "https://dih-fbn.com/",
        content: "Vincent has multiple professional experiences in developing and deploying digital solutions: originally in industrial logistics within the automotive industry and in the food &amp; beverage industry, then as consultant for a wide variety of SMEs and finally as entrepreneur involved in the creation of new businesses. In order to contribute to the development of its regional innovative ecosystem to support the digital transition and innovation, in 2014, Vincent co-founded the association Faubourg Numérique, of which he is now president. With this entrepreneurial impulse, Faubourg Numérique is committed to the FIWARE initiative as an Innovation Hub and involved in the future EDIH Sumity. Vincent is a certified FIWARE expert, i4Trust LEBD, and DIH2 LER.", linkedin: "https://www.linkedin.com/in/vincent-demortier-fr/", twitter: "https://twitter.com/VincDemortier", domain: "", location: "",
        flag: "", },
    "ulrich-ahle":
        { name: "Ulrich Ahle", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ulrich-ahle.jpg", position: "Chief Executive Officer", company: "Gaia-X", "company-link": "https://gaia-x.eu/",
        content: "Ulrich Ahle (m) is a reputed executive in the industrial sector, formerly Vice President and leader of Manufacturing, Retail &amp; Transportation business and responsible for Industry 4.0 at Atos in Germany. He is also founder and member of the Board of the International Data Spaces Association in Germany and served 16 years in the Board of prostep ivip, until April 2018. After an apprenticeship as toolmaker at Hella KG, he studied Mechanical Engineering at the University of Paderborn. In his career, Ulrich held several positions as development engineer, Director of PLM services, Sales Director and Vice President. He has been part of Nixdorf Computer AG, Siemens and Atos. From November 2016 to December 2023, Ulrich acted as Chief Executive Officer of FIWARE Foundation. Since January 2024 he is the CEO of Gaia-X.", linkedin: "https://de.linkedin.com/in/ahlefiware", twitter: "https://twitter.com/UlrichAhle", domain: "", location: "",
        flag: "", },
    "lars-nagel":
        { name: "Lars Nagel", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lars-nagel.jpg", position: "Chief Executive Officer", company: "IDSA", "company-link": "https://internationaldataspaces.org/",
        content: "Lars Nagel is CEO of the International Data Spaces Association since it’s foundation in 2016. He is also a member of the Executive Board of Digital Hub Management GmbH, where he manages innovation and technology transfer. Previously, Lars founded and led GlobalGate, a provider of learning environments for industrial and research institutions. Lars studied mechanical engineering at the Technical University of Dortmund and graduated with a diploma in engineering.", linkedin: "https://www.linkedin.com/in/lars-nagel-704411b8/", twitter: "https://twitter.com/larsmnagel", domain: "", location: "",
        flag: "", },
    "ana-garcia-robles":
        { name: "Ana Garcia Robles", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ana-garcia-robles.jpg", position: "Chief Executive Officer", company: "BDVA", "company-link": "https://www.bdva.eu/",
        content: "Secretary General of the Big Data Value Association (BDVA), holds a Masters Degree in Telecommunications Engineering and an International Executive MBA. Ana has a strong ICT industrial background in the Telecommunications sector, with over 10 years’ experience in the design, implementation and configuration of large-scale telecom networks and services, and in the research and techno-economical assessment of new technologies and solutions for large-scale implementation. Ana has specialised in Innovation management and ecosystems, and she has an extensive experience at both local/regional and international level in Open innovation ecosystems, Living Labs, and socio-economic impacts of technology with over 5 years’ experience managing international associations and projects in this area.", linkedin: "https://www.linkedin.com/in/ana-garcia-robles-9750641/", twitter: "https://twitter.com/roblesag", domain: "", location: "",
        flag: "", },
    "rocío-díaz-pereira":
        { name: "Rocío Díaz Pereira", img: "https://www.fiware.org/wp-content/directories/people/images/200px/rocio-diaz-pereira.jpg", position: "Hub Manager", company: "La Lonja Tech", "company-link": "https://lalonja.tech/en/",
        content: "Rocio is an Industrial engineer with masters in control engineering electronics systems as well as another in industrial maintenance engineering. She obtained all of her qualifications at the University of Huelva. She has developed her career as a Project Manager in the industrial sector. Attending to tasks such as cost control, people management and data analysis in corporations such as Enagas, Impala Terminals or Tioxide. She has in intense focus on continuous improvement of processes and looking for new technological solutions in order to optimize operations. In February of 2022, she decided to take on a different challenge in her professional career by taking over the direction of La Lonja de la Innovación, a world first FIWARE iHub specialising in the port sector. Her main goal is to develop a port innovation ecosystem, which is a programme designed to attract talent and give opportunities to pilot solutions in the port of Huelva.", linkedin: "https://www.linkedin.com/in/roc%C3%ADo-d%C3%ADaz-pereira-62978851/", twitter: "", domain: "", location: "",
        flag: "", },
    "gerard-van-der-hoeven":
        { name: "Gerard van der Hoeven", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gerard-van-der-hoeven.jpg", position: "Chief Executive Officer", company: "iSHARE Foundation", "company-link": "https://ishare.eu",
        content: "Gerard is an entrepreneur, venture builder and senior executive with over 25 years of entrepreneurial experience in the Tech industry. Been founding, building and scaling ventures in consulting, software, telecom, utility, electronics, and payments.", linkedin: "https://www.linkedin.com/in/gerardvdhoeven", twitter: "", domain: "", location: "",
        flag: "", },
    "dasha-davies":
        { name: "Dasha Davies", img: "https://www.fiware.org/wp-content/directories/people/images/200px/dasha-davies.jpg", position: "President", company: "Stealth-ISS Group", "company-link": "https://stealth-iss.com/",
        content: "As a global cybersecurity consultant/CISO, President of Stealth-ISS Group Inc., and Board Advisor on several cyber security technology and consulting service delivery companies, Dasha is an expert in cybersecurity operations, delivery risk, and compliance and a U.S. Navy veteran. With over 25 years of experience as a technology professional, she shaped cybersecurity practices within the US Defense Industry, NATO, various national and international government agencies, and the and the commercial sector, ensuring the security of sporting events as significant as the Olympic Games and Formula 1. Her expertise is in cybersecurity, GRC, incident response, smart cities, artificial intelligence, national security/cyber warfare, and C4I services. She has a bachelor&#x27;s degree in International Relations and Foreign Affairs, a MBA, and a MSc in Information Technology and Management and Cybersecurity, respectively, complemented by her pursuit of a Doctorate in Business and a PhD (ABD) in Cyber Warfare and National Security. Her authority in cybersecurity is underscored by a suite of certifications such as CISSP, C|CISO, NSA/IAM/IEM, and CMMC CCA, among others, and by being honored as one of the Top 100 CISOs in 2020. Her voice is respected at global conferences and events where she has presented on topics including cyber security, data protection, AI, and smart cities. She is a published author of &quot;Beyond Binary: AI and Cybersecurity,&quot; with upcoming books on cyberwarfare and national security and &quot;Navigating in the Cyber and AI Unknown.&quot;", linkedin: "", twitter: "", domain: "", location: "",
        flag: "", },
    "luka-keseri-":
        { name: "Luka Keserič", img: "https://www.fiware.org/wp-content/directories/people/images/200px/luka-keseric.jpg", position: "Marketing &amp; Demonstrator Manager", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "Luka Keseric (m) is a forward-thinking Computer Science master&#x27;s student, deeply passionate about cutting-edge technologies, particularly in the fields of AI, IoT, and Smart Cities. He has completed a Bachelor&#x27;s degree in Electrical Engineering and is currently finishing his Master’s degree in Computer Science at the University of Ljubljana. His technical skills encompass expertise in Machine Learning and IoT development, proficiency in programming languages such as C, C++ and Python, and hands-on experience with Microcontrollers like Arduino, ESP32, and ESP32-CAM. In his previous three-year role as a Research Assistant at the Laboratory for Machine Intelligence at the University of Ljubljana, Luka played a pivotal role in computer vision research, focusing on generative image models such as GANs and Diffusion models. Additionally, he served as a Project Leader and Board Member for a local NGO in Slovenia, where he spearheaded the development of public health and sustainable development workshops for both local and international students. Luka&#x27;s unique blend of technical expertise, leadership capabilities, and effective communication skills positions him as an excellent Smart World demonstrator and developer at FIWARE.His personal attributes include commitment to academic pursuits while actively contributing to impactful projects. He is known for his exceptional collaboration and communication skills and his visionary thinking with commitment to shaping the future through innovative technology solutions set him apart.", linkedin: "https://www.linkedin.com/in/luka-keseri%C4%8D-426164260/", twitter: "", domain: "", location: "",
        flag: "", },
    "roberto-di-bernardo":
        { name: "Roberto Di Bernardo", img: "https://www.fiware.org/wp-content/directories/people/images/200px/roberto-di-bernardo.jpg", position: "Head of Open Government R&amp;D Unit", company: "Engineering", "company-link": "https://www.eng.it/en/",
        content: "Roberto Di Bernardo is Senior Researcher and Head of the Open Government R&amp;D Group (part of Open Public Service Innovation Lab). He is an Electronic Engineer with Professional Master’s diplomas in “Clinical Engineering” and in “Internet Software Engineering”. He has been working as researcher at Engineering R&amp;D Laboratory since 2004, being involved in management and technical activities in many Italian and European projects. He is also acting as R&amp;D opportunity and network developer for the entire Public Sector R&amp;D area. At the moment, he is coordinating URBANAGE project (H2020-DT-Transforations-02) and his group is leading/involved in, among others, the following projects: DECIDO (H2020-DT-Governance-12), INTERSTAT (CEF-Public Open Data), SPOTTED (CEF-Public Open Data), ACROSS (H2020-DT-Governance-05), URBANITE (H2020-DT-Transformations-02). Currently he is leading the Smart Governance and Smart Cities sub-group of the Big Data Value Association and co-leading the Smart Cities Domain Committee of the FIWARE Foundation and the Digital Water Systems Working Group of Water Europe.", linkedin: "https://www.linkedin.com/in/robertodibernardo/", twitter: "", domain: "", location: "",
        flag: "", },
    "antonio-jara":
        { name: "Antonio Jara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonio-jara.jpg", position: "General Manager Smart Cities", company: "Libelium", "company-link": "https://www.libelium.com/",
        content: "Antonio has a PhD from the University of Murcia (Spain) and a MBA from the ENAE business school and UCAM (2012). He has received entrepreneurship awards from ENAE, emprendeGo, IPSO Alliance Award for its disruptive innovation in the IoT. As part of HOP Ubiquitous, Jara is focused on the Smart Cities market with solutions for citizens engagements, tourism, active participation, physical web and environmental monitoring (air quality sensors) in projects such as ENIAC SAFESENS, interoperability / pilots (SmartSDK, Synchronicity, Organicity, BeinCPPS) and also in several actions related to security/privacy (INPUT and FORTIKA).", linkedin: "https://www.linkedin.com/in/jara-libelium/", twitter: "https://twitter.com/antonio_jara", domain: "", location: "",
        flag: "", },
    "martin-bauer":
        { name: "Martin Bauer", img: "https://www.fiware.org/wp-content/directories/people/images/200px/martin-bauer.jpg", position: "Senior Researcher", company: "NEC Lab Europe", "company-link": "https://www.neclab.eu/",
        content: "", linkedin: "https://www.linkedin.com/in/martin-bauer-a722141/", twitter: "", domain: "", location: "",
        flag: "", },
    "antonio-filograna":
        { name: "Antonio Filograna", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonio-filograna.jpg", position: "Researcher", company: "Engineering", "company-link": "https://www.eng.it/en/",
        content: "Antonio is an expert in ICTs with special skills in areas like Open &amp; eGovernment, Social Innovation, Smart City, Data Protection and Privacy-preserving technologies, Cloud Computing, Architectural Design, Policy making. He has been involved in several European and Italian research projects dealing with several domains (public service for PA, smart mobility, smart environment, energy, FIWARE architecture) as project manager, technical designer, work package and task leader. At present, he is the Project Coordinator of DECIDO project (H202-SC6-GOVERNANCE-2020), he is also involved in SPOTTED project (CEF-TC-2020-2 Public Open Data; 2021-2024) as project leader and REBUILD project (H2020-DT-MIGRATION-06-2108 – Grant 822215) as work package leader.", linkedin: "https://www.linkedin.com/in/antoniofilograna/", twitter: "https://twitter.com/afilograna", domain: "", location: "",
        flag: "", },
    "sebastian-blechmann":
        { name: "Sebastian Blechmann", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sebastian-blechmann.jpg", position: "Research Associate", company: "RWTH Aachen", "company-link": "https://www.rwth-aachen.de/",
        content: "Sebastian Blechmann is working as research associate at the Institute for Energy Efficient Buildings and Indoor Climate in the E.ON Energy Research Center of the RWTH Aachen University. He is member of a research group targeting digital energy neighborhoods and specializes in semantic interoperability and efficient data utilization. In his research, he applies FIWARE to handle data from building energy systems, structure them semantically and apply control algorithms to control various test facilities. Thereby, he focuses on control and knowledge representation in heating, ventilation and air conditioning systems. In his presentation, he will talk about his past and present developments in the building energy sector using FIWARE.", linkedin: "https://www.linkedin.com/in/sebastian-blechmann-a2b19a119/", twitter: "", domain: "", location: "",
        flag: "", },
    "franck-le-gall":
        { name: "Franck Le Gall", img: "https://www.fiware.org/wp-content/directories/people/images/200px/franck-le-gall.jpg", position: "Chief Executive Officer", company: "Easy Global Market", "company-link": "https://www.egm.io/en/egm-the-innovation-factory",
        content: "Franck Le Gall is CEO at Easy Global Market, an innovative SME focused on integration and validation of emerging technologies. He is driving company development to deploy IoT and data technologies over vertical markets (water, agriculture, smart territories, environment, etc.). He involves himself in the standardization area including ETSI where he is co-chairman of the ETSI ISG-CIM working group on NGSI-LD. He is also chairing the interfaces working group of the FIWARE Technical Steering Committee (TSC) as well as the joint ETSI-FIWARE Foundation working group on Digital Twins. Finally, he is the Co-chair of the Smart Water working group of the ICT4Water European research cluster. He continuously contributes and drives several projects for public and private customers.", linkedin: "https://www.linkedin.com/in/francklegall/", twitter: "https://twitter.com/franck_le_gall", domain: "", location: "",
        flag: "", },
    "iffat-tariq":
        { name: "Iffat Tariq", img: "https://www.fiware.org/wp-content/directories/people/images/200px/iffat-tariq.jpg", position: "Chief Digital Officer", company: "I&amp;I Software Inc", "company-link": "https://www.iandisoft.com/",
        content: "With over two decades of experience, Iffat Tariq, Chief Digital Officer, has pioneered diverse digital initiatives globally. Specializing in Smart Cities and the Public Sector, she is instrumental in assisting governments at the forefront of data utilization and evidence-based decision-making, paving the way for excellence through digitization. With her extensive experience in developing modern data platforms for state and local governments, Iffat has become a trusted advisor in the government data landscape. Her expertise in bringing people, process, and technology together with an underlying foundation of data has transformed cities to move beyond pockets of excellence to citywide scale, sustainability, and resident impact. Iffat&#x27;s advisory role in the government data sector earned recognition at the Arizona Digital Government Summit 2023 in the session &#x27;My Data + Your Data &#x3D; Our Data.&#x27; She holds several industry certifications and international awards including &quot;ALM-Women’s Leaders in Consulting Award 2023&quot; and The International Awards Associate (IAA) 2023 due to her innovation and technology contributions in the public sector.", linkedin: "https://www.linkedin.com/in/iffattariq/", twitter: "", domain: "", location: "",
        flag: "", },
    "ilaria-bortone":
        { name: "Ilaria Bortone", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ilaria-bortone.png", position: "Program Manager", company: "Meditech 4.0", "company-link": "https://meditech4.com/",
        content: "Biomedical engineer with strong expertise overseeing and managing national and international funded research projects. She is a Senior Project Manager at Meditech 4.0 Competence Center, with a mandate on EU Partnerships. Technical Coordinator of MISTRAL (GA 101095119, doi: 10.3030/101095119), an EU-funded project aimed at developing a technological toolkit for dynamic, intelligent prediction of health-related features, forecasting the trajectories of disability and quality of life reduction. More than 10 years of experience with physiological data acquisition, logging and analysis. Her research interests focus on developing new technology-driven methods and algorithms to improve diagnosis, treatment and follow-up. Active scientific collaboration with the University of Bari Aldo Moro, the Institute of Clinical Physiology, the Polytechnic University of Bari, and Scuola Superiore Sant’Anna. Adjunct Professor in Biomechanics and Bioengineering at the School of Medicine, University of Bari, mentoring PhD students. Author and co-author of over 80 publications in International Journals and Proceedings of National and International Conferences (Scopus, H-index: 16). She has been awarded several international acknowledgements (Group Study Exchange Rotary Foundation, Startcup Puglia 2016) and prizes (Ministry of Education University and Research, Tuscany Region, Ministry of Enterprises and Made in Italy, HORIZON EUROPE). She led two nationally-funded research projects (KISS-HEALTH, 2012-15, PON04a3_00097; TELOS, 2020-24, CUP J53D23005710006).", linkedin: "https://www.linkedin.com/in/ilaria-bortone-0461a146/", twitter: "", domain: "", location: "",
        flag: "", },
    "sophie-meszaros":
        { name: "Sophie Meszaros", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sophie-meszaros.jpg", position: "Project Manager", company: "OASC", "company-link": "oascities.org",
        content: "Sophie is a project coordinator and research advisor at Open &amp; Agile Smart Cities (OASC). She oversees projects like the European Data Space for Smart Communities and the Living-in.EU initiative. As part of her work at OASC, she also coordinates the development of the Minimal Interoperability Mechanisms (MIMs). Her work supports the digital transformation of smart cities and communities, focusing on trust in technology within data spaces, local digital twins, and testing facilities. Using both qualitative and quantitative methods, Sophie translates her research into practical guidelines, requirements, and recommendations, including governance models and data management plans.", linkedin: "https://www.linkedin.com/in/sophiemeszaros/", twitter: "", domain: "", location: "",
        flag: "", },
    "jorge-hernandez":
        { name: "Jorge Hernandez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jorge-hernandez.jpg", position: "Chief Executive Officer", company: "Ignicion Games", "company-link": "https://www.igniciongames.com/",
        content: "CEO of Ignicion Games, a systems engineer with over 15 years of experience in the IT industry. Winner of the Indigo Experience for his software for interrelation, correlation, and analysis for smart cities based on Fiware. Designer of the crime prediction model on the country platform in Colombia along with a layer system in Fiware. Passionate about technology and video games.", linkedin: "https://www.linkedin.com/in/jorge-antonio-hernandez-sanchez-669b71b0/", twitter: "", domain: "", location: "",
        flag: "", },
    "tomohiro-kuwahara":
        { name: "Tomohiro Kuwahara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/tomohiro-kuwahara.jpg", position: "Senior Manager", company: "NEC Corporation", "company-link": "www.nec.com",
        content: "Tomohiro Kuwahara is a business development manager at NEC Corporation. He has over 15 years of business development experience in a wide range of fields such as Smart City, Biometrics, and IT/IoT. His current role involves promoting smart cities from both NEC&#x27;s and iHub Base&#x27;s perspective.", linkedin: "https://www.linkedin.com/in/tomohiro-kuwahara-37972616/", twitter: "", domain: "", location: "",
        flag: "", },
    "raza-jafri":
        { name: "Raza Jafri", img: "https://www.fiware.org/wp-content/directories/people/images/200px/raza-jafri.jpg", position: "Chief Executive Officer", company: "Metaworldx", "company-link": "https://www.metaworldx.com/",
        content: "Raza Jafri is a global entrepreneur, investor, and speaker, he is the founder and Chief Executive Officer of MetaWorldX, a world-class AI digital twin technology company that creates immersive and realistic simulations of urban environments for smart cities, cleantech, and other sectors. He launched MetaWorldX at the World Smart City Congress in Barcelona, Spain, and received the Top 40 Under 40 Sustainability Star Award for 2023 for his innovative and impactful work.", linkedin: "https://www.linkedin.com/in/razajafri", twitter: "", domain: "", location: "",
        flag: "", },
    "giovanni-vaglica":
        { name: "Giovanni Vaglica", img: "https://www.fiware.org/wp-content/directories/people/images/200px/giovanni-vaglica.jpg", position: "IT Engineer", company: "JRC – EC", "company-link": "https://joint-research-centre.ec.europa.eu",
        content: "Giovanni Vaglica is an IT engineer, specialised in the development and implementation of Smart City systems and smart infrastructures. He is responsible of the technical implementation and development of the Smart City digital platform test-bed of the EC Joint Research Centre - E.3 Unit, Safety and Security of Buildings, aimed at developing and testing technologies and solutions in real-world urban environment scenarios. As the platform&#x27;s architect, he carries out research and development to develop scalable and interoperable solutions to support Smart city applications for critical infrastructures. Additionally, the integration of heterogeneous IoT sensors and wireless networks in a very secure networking environment is a key focus of his work.", linkedin: "linkedin.com/in/giovanni-vaglica-55103a197", twitter: "", domain: "", location: "",
        flag: "", },
    "mireya-de-diego":
        { name: "Mireya de Diego", img: "https://www.fiware.org/wp-content/directories/people/images/200px/mireya-de-diego.png", position: "EU Project Coordinator", company: "CARTIF", "company-link": "https://www.cartif.es/en/home/",
        content: "Mireya de Diego (f), MSc.Eng in Industrial Electronics and Automation and Degree in Telecommunications Engineering from the University of Valladolid (Spain). Since 2013, she has been a researcher in the CARTIF Industrial and Digital Systems Division, specializing in robotic, automation and process control within the agri-food manufacturing industry. In the field of process control, she has contributed to projects such as CAPRI, ECOFACT and REGENby2, driving innovation and sustainability across various industrial sectors. Currently serves as the coordinator for the ARISE project, focusing on the HRI - human-robot interaction in diverse sectors, including manufacturing, logistic and healthcare.", linkedin: "https://www.linkedin.com/in/mireya-de-diego/", twitter: "", domain: "", location: "",
        flag: "", },
    "andrea-maioli":
        { name: "Andrea Maioli", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-maioli.jpg", position: "Postdoctoral Researcher", company: "Politecnico di Milano", "company-link": "https://www.polimi.it/",
        content: "Andrea Maioli is a postdoctoral researcher at the Network Embedded Software Lab of Politecnico di Milano (Italy). His current research focuses on smart cities and embedded systems, with particular emphasis on enabling a battery-free computation for the embedded systems powering the Internet of Things.", linkedin: "https://www.linkedin.com/in/andrea-maioli-300a2070/", twitter: "", domain: "", location: "",
        flag: "", },
    "francesco-mureddu":
        { name: "Francesco Mureddu", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francesco-mureddu.jpg", position: "Senior Director", company: "The Lisbon Council", "company-link": "https://lisboncouncil.net/",
        content: "Francesco Mureddu is a leading analyst on innovation and technology policies with a special focus on digital transformation, big data, artificial intelligence, eGovernment, smart cities, social innovation, future science and citizen science. He holds a PhD in economics from the University of Cagliari and a master’s degree in economics from the Catholic University of Louvain.", linkedin: "https://www.linkedin.com/in/francescomureddu/", twitter: "", domain: "", location: "",
        flag: "", },
    "luigi-coppolino":
        { name: "Luigi Coppolino", img: "https://www.fiware.org/wp-content/directories/people/images/200px/luigi-coppolino.jpg", position: "Professor", company: "Parthenope University", "company-link": "https://www.uniparthenope.it/",
        content: "Luigi Coppolino is an Associate Professor at the University of Naples Parthenope. After his graduation in Computer Engineering at the University of Naples Federico II, in 2004 he got a Master degree in Dependable Architectures at the University of Campania Vanvitelli (former Second University of Naples). He moved to the industry with a quick experience at InCard Spa (currently ST Microelectronic) and Ansaldo Segnalamento Ferroviario (currently Hitachi Rail Italy) after that he moved back to the University where he got a Ph.D. degree in Computer Engineering from the University of Naples Federico II. In 2006 the TrustedSIM, javacard based project, developed by Mr. Coppolino, was one of the winners of the 7th SIMAGINE contest, sponsored by Axalto, SUN Microsystems, and Samsung. His research activity mainly focuses on dependability (performance/performability, reliability, availability, safety e security) of critical networked computing systems, such as telemedicine, e-government, and video surveillance applications, or avionics, railways, and automotive systems. During his Ph.D, Mr. Coppolino was at the University of New South Wales (Sydney), as Visiting Researcher, working with prof. Branko Celler’s research group to the security of the Home Telecare system developed and distributed by prof. Branko Celler’s research group. Luigi Coppolino is/has been engaged in several research projects funded by the European Community in the framework of FP7 and H2020 funding programs. He is indeed the Technical Coordinator of the COMPACT research project and he was leading was one of the principal investigators of the projects STREAM (Scalable Autonomic Streaming Middleware for Real-time Processing of Massive Data Flows), Grant agreement no. 216181, INTERSECTION (INfrastructure for heTErogeneous, Resilient, SEcure, Complex, Tightly Inter-Operating Networks), Grant agreement no. 216585, INSPIRE (INcreasing Security and Protection through Infrastructure Resilience), Grant agreement no. 225553, MASSIF (MAnagement of Security information and events in Service InFrastructures), Grant agreement no. 257475, SAWSOC (Situation AWare Security Operations Center), Grant agreement no. 313034, LeanBigData, Grant agreement no. 619606, SERECA (Secure Enclaves for REactive Cloud Applications), KONFIDO (Secure and Trusted Paradigm for Interoperable eHealth Services), Grant agreement no. 727528.", linkedin: "https://www.linkedin.com/in/luigi-coppolino-0701366/", twitter: "", domain: "", location: "",
        flag: "", },
    "jesús-ruiz-martinez":
        { name: "Jesús Ruiz Martinez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jesus-ruiz.jpg", position: "Chief Technology Officer", company: "Alastria", "company-link": "https://alastria.io/en/",
        content: "Member of the board and CTO of Alastria Blockchain Ecosystem, participates in the Technical Governance of EBSI (European Blockchain Services Infrastructure from European Commission and Member States), and in LACChain (blockchain network promoted by the Inter-American Development Bank). He inspired the Public-Permissioned model followed by those networks, where decentralized governance and SSI are critical components.", linkedin: "https://www.linkedin.com/in/jesus-ruiz-martinez/", twitter: "", domain: "", location: "",
        flag: "", },
    "yuzhen-li":
        { name: "Yuzhen Li", img: "https://www.fiware.org/wp-content/directories/people/images/200px/yuzhen-li.jpg", position: "Demonstrator Manager", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
        content: "Yuzhen Li (f) is a working student as a Lego Smart World developer &amp; demonstrator. She completed her BEng in Electronic Information Engineering and now is close to finishing her master&#x27;s degree in the same field (ICT-Telecommunication) at TU Berlin. Her interests and expertise mainly focus on Cloud-Computing, Network Engineering, and DevOps. Before joining FIWARE, she has 2-years of experience in handling massive global network traffic and data centers for the large music streaming platform SoundCloud as a Network Reliability Engineer. Now she is working on improving the software system (Docker, VMs, Database, NGSI, etc.) for LEGO models to make it better connected to FIWARE Technologies.", linkedin: "https://www.linkedin.com/in/yuzhen-li-b242421a4/", twitter: "", domain: "", location: "",
        flag: "", },
    "antonella-longo":
        { name: "Antonella Longo", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonella-longo.jpg", position: "Professor", company: "University of Salento", "company-link": "https://sydalab.unisalento.it/en/",
        content: "Antonella Longo, is an Professor at the Department of Engineering for Innovation of the University of Salento. She received the PhD in Information Engineering in 2004. She teaches Data Management and Big data management at the school of Engineering. Her research interests deal with information systems and databases, service-oriented architectures design for cloud infrastructure, technology-enhanced learning and citizen science. Her current research activity focuses on big data management and investigation of cloud architectures integration with edge computing in cyber-physical social systems. She is currently involved in a number of projects for developing data spaces for digital twins of cities and energy systems. On these topics, she has published more than 100 papers in peer-reviewed journals and international conference proceedings. She coordinate the SyDA – Lab at University of Salento.", linkedin: "https://www.linkedin.com/in/antonellalongo", twitter: "", domain: "", location: "",
        flag: "", },
    "nejib-moalla":
        { name: "Nejib Moalla", img: "https://www.fiware.org/wp-content/directories/people/images/200px/nejib-moalla.jpg", position: "Professor", company: "Université Lumière Lyon 2", "company-link": "https://welcome.univ-lyon2.fr/",
        content: "Prof. Nejib Moalla, received a master degree in Computer Science. He finished his Ph.D. thesis in 2007 and hisnhabilitation in 2015. He held the responsibility of the project management department between 2008 and 2012. His research activities deal with software and data engineering to support digital transformation with finalised solutionsin Manufacturing, Healthcare, Smart Farming, etc. In software engineering, the developed research concepts and solutions cover: software quality, service-oriented architectures, microservice architecture, performance-based service reuse, service personalisation, ontology engineering, knowledge management, decision support, etc. In data engineering, the research activities cover: the application of data-driven artificial intelligence technics (Machine Learning, etc.) to support decision-making processes in a digital twin perspective. Nejib Moalla is in charge of the DIH ICT4Manuf. As a project manager, he coordinates regional industrial projects and continues to be involved in different collaborative and international projects: H2020 DIH4CPS (2020-2022), EPlus ENHANCE (2021-2024, Coordinator), EPlus TETRIS (2021-2024), H2020 vf-OS (2017-2019), FIPPP FP7 FITMAN (2013-2015), etc. He is a member of several international program committees (IPC) of international journals and conferences.", linkedin: "https://www.linkedin.com/in/n%C3%A9jib-moalla-7b846513/", twitter: "https://twitter.com/nejib_moalla", domain: "", location: "",
        flag: "", },
    "antonello-monti":
        { name: "Antonello Monti", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonello-monti.jpg", position: "Professor &amp; Institute Director", company: "RWTH Aachen University", "company-link": "https://www.rwth-aachen.de/go/id/a/?lidx&#x3D;1",
        content: "Prof. Antonello Monti received his M.Sc degree (summa cum laude) and his PhD in Electrical Engineering from Politecnico di Milano, Italy in 1989 and 1994 respectively. He started his career in Ansaldo Industria and then moved in 1995 to Politecnico di Milano as Assistant Professor. In 2000 he joined the Department of Electrical Engineering of the University of South Carolina (USA) as Associate and then Professor. Since 2008 he is the director of the Institute for Automation of Complex Power System within the E.ON Energy Research Center at RWTH Aachen University. From 2019 he holds a double appointment with Fraunhofer FIT where he is developing the new Center for Digital Energy in Aachen. Prof. Monti is author or coauthor of more than 400 peer-reviewed papers published in international Journals and in the proceedings of International conferences. He is a Senior Member of IEEE, Associate Editor of the IEEE System Journal, Associate Editor of IEEE Electrification Magazine, Member of the Editorial Board of the Elsevier Journal SEGAN and member of the founding board of the Springer Journal “Energy Informatics”. Dr. Monti was the recipient of the 2017 IEEE Innovation in Societal Infrastructure Award.", linkedin: "https://www.linkedin.com/in/antonellomonti/", twitter: "", domain: "", location: "",
        flag: "", },
    "luis-muñoz":
        { name: "Luis Muñoz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/luis-munoz.jpg", position: "Professor", company: "University of Cantabria", "company-link": "https://web.unican.es/en/Pages/default.aspx",
        content: "Prof. Luis Muñoz received both the Telecommunications Engineering degree and Ph.D. from the Polytechnical University of Cataluña (UPC), Spain. He also holds a Master in Mathematics, Statistic and Operation Research (Licenciado en Ciencias Matemáticas, UNED). His research focuses on advanced data transmission techniques, heterogeneous wireless multihop networks, Internet o Things, technologies and services in the context of smart cities and applied mathematical methods for telecommunications. He has participated in several National and European research projects belonging to the 4th, 5th, 6th and 7th and H2020 Framework Program in which he was technical manager of SmartSantander. He has published over 150 journal and conference papers. He serves as editor of several journals and he has been invited to participate in the Steering Committee and Technical Program Committee of the most relevant international conferences. In parallel to this activity, he serves as consultant for the Spanish Government as well as for different companies in Europe. Last but not least, he has served as an expert of the ETSI and European Commission.", linkedin: "", twitter: "", domain: "", location: "",
        flag: "", },
    "matteo-repetto":
        { name: "Matteo Repetto", img: "https://www.fiware.org/wp-content/directories/people/images/200px/matteo-repetto.png", position: "Senior Researcher", company: "CNR / IMATI", "company-link": "https://www.imati.cnr.it/make_home_page.php?language&#x3D;ENG&amp;view&#x3D;GEN",
        content: "Matteo Repetto, Ph.D., received the Ph.D. degree in Electronics and Computer Science in 2004 from the University of Genoa. From 2004 to 2009 he was a postdoc at University of Genoa. From 2010 to 2019 he was a Research Associate at CNIT. In 2019 he joined the Institute for Applied Mathematics and Information Technologies (IMATI), CNR, where he currently holds a Senior Researcher position. He has been teaching many courses in telecommunication networks and network security. He has been involved in several research national and international projects on quality of service, mobility in data networks, energy efficiency, cloud computing, and network function virtualization. He was the scientific and technical coordinator of the ASTRID and GUARD projects, and he is now the coordinator of the MIRANDA project. He has co-authored over 90 scientific publications in international journals and conference proceedings, and 1 technical report for ITU. His current research interests include security architectures, interfaces to remote security functions, network security, threat hunting, management and security of digital service chains.", linkedin: "https://www.linkedin.com/in/matteo-repetto-1b00134/", twitter: "", domain: "", location: "",
        flag: "", },
    "joaquín-salvachúa":
        { name: "Joaquín Salvachúa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/joaquin-salvachua.jpg", position: "Professor", company: "UPM", "company-link": "https://www.upm.es/internacional",
        content: "Prof. Joaquín Salvachúa received a master degree in Computer Science. He holds the Orange Chair for the “Science of Complex Networks” and the Kairos Chair on “Bank Middleware and Blockchain” at UPM and is a member of the UPM-ING and CyberAula groups. He has participated in several European research projects with several publications at international magazines, books and conferences. (https://orcid.org/0000-0002-7269-8079). Also have participated in several standardization activities, including been coauthor one RFC ( RFC 8802 ).His research focuses today on WebRTC, Cloud infrastructure, social graphs and recommendation, agile cloud infrastructures, P2P, DHT (Distributed HashTables), IOT, Non SQL Data Bases, Big data processing architectures, Identity Management and BlockChain distributed agreement algorithms.His teaching duties includes cloud computing, distributed application development, Databases, Web Full-stack development, Blockchain architecture, Data Engineering and Big data architecture and applications. Has been involved in the FIWARE Initiative since it started (2010) and he is architect and developer of several GE related to security, data persistence and Big Data analysis.", linkedin: "https://es.linkedin.com/in/jsalvachua", twitter: "https://twitter.com/jsalvachua", domain: "", location: "",
        flag: "", },
};