var companies = [
        'Adani',
        'Agricolus',
        'Arsys',
        'Atilim University',
        'AUSTRALO',
        'City of Vienna',
        'DigitalTwin Technology',
        'ECOEMBES',
        'Engineering',
        'EPPO',
        'Faubourg Numérique',
        'FIWARE',
        'FIWARE Foundation',
        'FundingBox',
        'Future Intelligence',
        'Hearing Software',
        'Helix',
        'Hopu – Libelium',
        'Huawei R&amp;D',
        'i2CAT Foundation',
        'Impact Funding Europe',
        'Innovalia',
        'IOTA Foundation',
        'iP-NETs',
        'ITAM',
        'JIG',
        'Martel Innovation',
        'NEC Corporation',
        'NEC Corporation India',
        'Secmotic',
        'TeamDev',
        'Telefónica',
        'Thales Group',
        'Tribr',
        'UFU',
        'Universidad Politécnica de Madrid',
        'University Gaston Berger',
        'WOBCOM',
]; var departments = [
]; var domains = [
]; var titles = [
        'Assistant Professor',
        'Associate General Manager',
        'Associate Professor',
        'Business Architect',
        'Business Development Manager',
        'CDTO',
        'CEO',
        'Chief Architect',
        'Chief Executive Officer',
        'Cloud Expert',
        'Co-Founder',
        'COO',
        'Coordinator',
        'CSO',
        'CTO',
        'Deputy Director',
        'Developer',
        'Director',
        'Evangelist',
        'Expert',
        'FIWARE Manager',
        'Founder',
        'Full Professor',
        'Head of Communities',
        'Innovation Specialist',
        'Manager',
        'ML Specialist',
        'Platform Expert',
        'President',
        'Product Manager',
        'Programme Lead',
        'Project Manager',
        'R&amp;D Security Architect',
        'Researcher',
        'Software Architect',
        'Solution Architect',
        'Technical Expert',
]; var countries = [
]; var modalData = [
    { name: "Abhinav Praween Agrawal", img: "https://www.fiware.org/wp-content/directories/people/images/200px/abhinav-praween-agrawal.jpg", position: "Chief Architect", company: "Adani", "company-link": "https://www.adani.com/",
    content: "", linkedin: "https://www.linkedin.com/in/abhitechie/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Ulrich Ahle", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ulrich-ahle.jpg", position: "Chief Executive Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Ulrich Ahle (m) is a reputed executive in the industrial sector, formerly Vice President and leader of Manufacturing, Retail &amp; Transportation business and responsible for Industry 4.0 at Atos in Germany. He is also founder and member of the Board of the International Data Spaces Association in Germany and served 16 years in the Board of prostep ivip, until April 2018. After an apprenticeship as toolmaker at Hella KG, he studied Mechanical Engineering at the University of Paderborn. In his career, Ulrich held several positions as development engineer, Director of PLM services, Sales Director and Vice President. He has been part of Nixdorf Computer AG, Siemens and Atos. Since January 2017, Ulrich acts as Chief Executive Officer of FIWARE Foundation.", linkedin: "https://de.linkedin.com/in/ahlefiware", twitter: "https://twitter.com/UlrichAhle", domain: "", location: "",
    flag: "", },
    { name: "Álvaro Alonso", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alvaro-alonso.jpg", position: "Assistant Professor", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "Álvaro Alonso is currently an Assistant Professor with the UPM. His research interests include Multi Video Conferencing Systems, Security Management in Smart Context scenarios, and Public Open Data.", linkedin: "https://www.linkedin.com/in/alvaroalonsogonzalez", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Thais Batista", img: "https://www.fiware.org/wp-content/directories/people/images/200px/thais-batista.jpg", position: "Full Professor", company: "Innovalia", "company-link": "https://www.ufrn.br/en",
    content: "", linkedin: "https://www.linkedin.com/in/thais-batista-58b9b94a/", twitter: "https://twitter.com/thaisvbatista", domain: "", location: "",
    flag: "", },
    { name: "Ali Benbrahim", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ali-benbrahim.jpg", position: "Chief Executive Officer", company: "iP-NETs", "company-link": "http://www.ipnets.tn/",
    content: "", linkedin: "https://www.linkedin.com/in/ali-benbrahim-71203121/", twitter: "https://twitter.com/alibb0404", domain: "", location: "",
    flag: "", },
    { name: "José Benitez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-benitez.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "Secmotic", "company-link": "https://secmotic.com/",
    content: "", linkedin: "https://www.linkedin.com/in/jose-benitez-secmotic", twitter: "https://twitter.com/josesecmotic", domain: "", location: "",
    flag: "", },
    { name: "Marivi Briz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/maria-virtudes-briz.jpg", position: "Head Of Product Management", company: "Telefónica", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/mariavirtudesbriz/", twitter: "https://twitter.com/marivibriz", domain: "", location: "",
    flag: "", },
    { name: "José Manuel Cabello", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-manuel-cabello.jpg", position: "R&amp;D Director", company: "Innovalia", "company-link": "https://innovalia.org/en/",
    content: "", linkedin: "https://www.linkedin.com/in/jos%C3%A9-manuel-cabello-montesino-2936a479/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "José Manuel Cantera Fonseca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-manuel-cantera-fonseca.jpg", position: "Software Architect", company: "IOTA Foundation", "company-link": "https://www.iota.org/",
    content: "", linkedin: "https://www.linkedin.com/in/jmcanterafonseca/", twitter: "https://twitter.com/jmcantera", domain: "", location: "",
    flag: "", },
    { name: "Javier Carpintero Ordoñez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/javier-carpintero-ordonez.jpg", position: "Smartcities, IoT &amp; Industry 4.0 Manager", company: "NEC Corporation", "company-link": "https://www.nec.com/",
    content: "", linkedin: "https://www.linkedin.com/in/jacarpint/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Chandra Challagonda", img: "https://www.fiware.org/wp-content/directories/people/images/200px/chandra-challagonda.jpg", position: "Solution Architect", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Chandra Challagonda (m) is Senior Architect at FIWARE Foundation in Germany. Chandra holds a Masters in Software Engineering degree from 1999 - 2002. Chandra comes with nearly 25 years of experience in software development, integration projects and software product management. He worked for Ericsson and Nokia in various technical and non-technical roles in Network infrastructure and smartphones for 15 years. Chandra has been an active member of the FIWARE community since 2015 and joined FIWARE Foundation in 2019. In FIWARE Foundation, Chandra is the platform architect for SmartMaaS and IMPRESS projects funded by the German Federal government. Before joining FIWARE Foundation, he was part of the team which created a digital twin for Helsinki Transportation.", linkedin: "https://linkedin.com/in/challagonda", twitter: "https://twitter.com/challagonda", domain: "", location: "",
    flag: "", },
    { name: "Andrea Chiancone", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-chiancone.jpg", position: "Product Manager", company: "Agricolus", "company-link": "https://www.agricolus.com/",
    content: "", linkedin: "https://www.linkedin.com/in/andrea-chiancone-a3495a5/", twitter: "https://twitter.com/Antonio_Jara", domain: "", location: "",
    flag: "", },
    { name: "Ian Chong", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "Programme Lead &amp; Business Development", company: "Tribr", "company-link": "http://www.tribr.tech",
    content: "", linkedin: "https://www.linkedin.com/in/ianchongsg/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Giovanni Coppa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/giovanni-coppa.jpg", position: "Coordinator Astrid iHub", company: "WOBCOM", "company-link": "https://www.wobcom.de/",
    content: "More than 10 years of experience in Data Center and digital transformation. I am passionate about energy efficiency and environmental friendly technologies, with a strong interest in digital revolution and strategic innovation.", linkedin: "https://www.linkedin.com/in/giovannicoppa/", twitter: "https://twitter.com/korematic", domain: "", location: "",
    flag: "", },
    { name: "Andrea Cruciani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-cruciani.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "TeamDev", "company-link": "https://www.teamdev.it/en/",
    content: "Andrea is the Agricolus co-founder and CEO, member of FIWARE Foundation BoD, Chairman of the FIWARE Smart AgriFood MSC. He runs the international business area and the financial aspects of the company and he has a technical background and experience in applications Development, Enterprise Architectures, Cloud Computing, and GIS. Andrea is involved in Innovative Startup Evolution and scaleup, during the years he worked with Public Administration, multinational companies, NGOs, and SMEs. He is a speaker for several universities and public events where he is invited to discuss entrepreneurship and digital transformation, and he is a contributor in several technical articles and publications about agritech.", linkedin: "https://www.linkedin.com/in/andreacruciani/", twitter: "https://twitter.com/kokkete", domain: "", location: "",
    flag: "", },
    { name: "Cyril Dangerville", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "R&amp;D Security Architect", company: "Thales Group", "company-link": "https://www.thalesgroup.com/en",
    content: "", linkedin: "https://www.linkedin.com/in/cyril-dangerville-bb5a075/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Roi Rodriguez De Bernardo", img: "https://www.fiware.org/wp-content/directories/people/images/200px/roi-rodriguez-de-bernardo.jpg", position: "Director of AI &amp; Cloud Ecosystem", company: "Huawei R&amp;D", "company-link": "https://www.huawei.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/roirodriguezdebernardo/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Gabriele De Luca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gabriele-de-luca.jpg", position: "Senior Researcher", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Gabriele De Luca graduated as Doctor with Laude in Computer Engineering from the University of Salento. He has been working in the R&amp;D Lab for Engineering Ingegneria Informatica S.p.A. since 2014 as part of the “Digital Industry and Agrifood” Unit. He has been involved in different Italian and European research projects playing several roles, such as software developer, solution designer, system architect and information expert. Currently, he acts as Technology Manager and Team Leader. The main application fields are Advanced Manufacturing, Smart Farming, Supply Chain Management, Operational Intelligence, Artificial Intelligence, Internet of Things and Food Safety whereas the main activities are correlated to Event Processing, Sensor Data Processing (OGC standards such as Sensor Web Enablement), Decision Support Systems, Internet of Things (mainly in the FIWARE context), Data Sovereignty and Data Spaces (IDSA-based). His relevant expertise and experiences include Architecture Design, System Integration, and Collaborative Working Environment, from both software engineering and technological points of view. Main research fields are applied to Digital Industry, including Operational Intelligence (especially in Complex Event Processing and Process Mining), Supply Chain Integration, and so on.", linkedin: "https://www.linkedin.com/in/gabriele-de-luca-b4132861/", twitter: "https://twitter.com/gabrielede_luca", domain: "", location: "",
    flag: "", },
    { name: "Flávio de Oliveira Silva", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "Associate Professor", company: "UFU", "company-link": "https://ufu.br/",
    content: "", linkedin: "", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Stefano De Panfilis", img: "https://www.fiware.org/wp-content/directories/people/images/200px/stefano-depanfilis.jpg", position: "Chief Operations Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Stefano de Panfilis (m) is the Chief Operating Officer at FIWARE Foundation. He graduated cum laude in Mathematics at the University of Rome “La Sapienza”. In 1984, he was hired in Engineering Ingegneria Informatica S.P.A as a software engineer. In 1986, he became Project Manager to then move to the R&amp;D department managing the “Formal Methods” unit. In 1993, he supported Engineering to receive the ISO-9001 compliancy. From 1994, he was involved in European R&amp;D. He coordinated SeCSE (IST 6FP), aiming at implement a platform for Service-Centric Systems Engineering, CBSEnet (IST-5FP NoE), CLARiFi (IST 5FP), DOOR (ESPRIT 4FP), SQUAD (INCO-DC), and VALSE (TV&amp;TT) projects, and the ENG- SODEPRO, DECO’ and DOMINARE ESSI Process Improvement Experiments. He also coordinated QualiPSo (IST 6FP) aiming at leverage Open Source Software development to recognised industrial standards, leading a consortium of 20 partners from Europe, Brazil and China. He actively participated to create and set-up the NESSI ETP of which he is the Coordinator of the Strategic Research Agenda Committee. Since 2017, he is employed by FIWARE Foundation as Chief Operations Officer.", linkedin: "https://www.linkedin.com/in/stefano-de-panfilis-1928a11/", twitter: "https://twitter.com/depa01", domain: "", location: "",
    flag: "", },
    { name: "Vincent Demortier", img: "https://www.fiware.org/wp-content/directories/people/images/200px/vincent-demortier.jpg", position: "President", company: "Faubourg Numérique", "company-link": "http://faubourgnumerique.com/",
    content: "Vincent has multiple professional experiences in developing and deploying digital solutions: originally in industrial logistics within the automotive industry and in the food &amp; beverage industry, then as consultant for a wide variety of SMEs and finally as entrepreneur involved in the creation of new businesses. In order to contribute to the development of its regional innovative ecosystem to support the digital transition and innovation, in 2014, Vincent co-founded the association Faubourg Numérique, of which he is now president. With this entrepreneurial impulse, Faubourg Numérique is committed to the FIWARE initiative as an Innovation Hub and involved in the future EDIH Sumity. Vincent is a certified FIWARE expert, i4Trust LEBD, and DIH2 LER.", linkedin: "https://www.linkedin.com/in/vincent-demortier-fr/", twitter: "https://twitter.com/VincDemortier", domain: "", location: "",
    flag: "", },
    { name: "Gianluca Dianese", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gianluca-dianese.jpg", position: "Digital Transformation Officer", company: "EPPO", "company-link": "https://www.eppo.europa.eu/en",
    content: "", linkedin: "https://www.linkedin.com/in/gianlucadianese/", twitter: "https://twitter.com/gdianese", domain: "", location: "",
    flag: "", },
    { name: "Daniele Diodati", img: "https://www.fiware.org/wp-content/directories/people/images/200px/daniele-diodati.jpg", position: "ML Specialist", company: "TeamDev", "company-link": "https://www.teamdev.it/en/",
    content: "", linkedin: "https://www.linkedin.com/in/daniele-diodati/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Gonzalo Ezquerro Martínez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gonzalo-ezquerro-martinez.jpg", position: "Chief Technology Officer", company: "JIG", "company-link": "https://www.jig.es/",
    content: "", linkedin: "https://www.linkedin.com/in/gonzalo-ezquerro-mart%C3%ADnez-94818089/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Federico Facca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/federico-facca.jpg", position: "Chief Technology Officer", company: "Martel Innovation", "company-link": "https://www.martel-innovate.com/",
    content: "Federico is the CTO of Martel, leading internal IT projects and acting as strategic lead consultant to customers, including the European Commission. Federico’s current core project is Orchestra Cities, a modular and flexible cloud-native IoT platform (mostly used in the Smart City domain). He has an extensive experience on Cloud-Native architectures, Infrastructure as a Code approach, continuous testing and monitoring to ensure infrastructure reliability. He is a strong advocate of Open Source and thrive to use and contribute to Open Source solutions. In his career he lead different large R&amp;D projects, ranging from industrial systems integration to data center deployment and federation. Before joining Martel Innovate, Federico has been area head in different FBK-CREATE-NET and STI Innsbruck. He holds a PhD and MSc in Computer Science.", linkedin: "https://www.linkedin.com/in/federicofacca/", twitter: "https://twitter.com/chicco785", domain: "", location: "",
    flag: "", },
    { name: "Jason Fox", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jason-fox.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Jason Fox (m) has been working for FIWARE Foundation for the last five years in the role of technical evangelist, educating and diseminating information about NGSI interfaces, JSON-LD, Linked Data, the components within the FIWARE Catalogue and Securing FIWARE architectures. Before joining FIWARE, he worked as a software engineer for over 20 years in various roles both in Germany and the United Kingdom using a wide variety of programming languages ranging from C++ to Java to Node.js. This has included coding the software behind selling lottery tickets online for the British National Lottery, and and developing and maintaining technical documentation applications for Nokia.", linkedin: "https://www.linkedin.com/in/jason-fox-8a79563/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Juan Marcelo Gaitan Leiva", img: "https://www.fiware.org/wp-content/directories/people/images/200px/juan-marcelo-gaitan-leiva.jpg", position: "FIWARE Manager", company: "Telefónica", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/juanmarcelogaitan/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Fermín Galán Márquez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/fermin-galan-marquez.jpg", position: "Expert", company: "Telefónica", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/fermingalan/", twitter: "https://twitter.com/ermingalan", domain: "", location: "",
    flag: "", },
    { name: "Olaf-Gerd Gemein", img: "https://www.fiware.org/wp-content/directories/people/images/200px/olaf-gerd-gemein.jpg", position: "Business Architect", company: "Impact Funding Europe", "company-link": "https://impactfundingeurope.eu/",
    content: "", linkedin: "https://www.linkedin.com/in/olafgerdgemein/", twitter: "https://twitter.com/oggemein", domain: "", location: "",
    flag: "", },
    { name: "Jose Gonzalez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-gonzalez.jpg", position: "Chief Executive Officer", company: "AUSTRALO", "company-link": "https://www.australo.org/",
    content: "", linkedin: "https://www.linkedin.com/in/joseglezes/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Ignacio Gurría de la Torre", img: "https://www.fiware.org/wp-content/directories/people/images/200px/javier-gurria.jpg", position: "Chief Executive Officer", company: "JIG", "company-link": "https://www.jig.es/",
    content: "", linkedin: "https://www.linkedin.com/in/ignaciog3/", twitter: "https://twitter.com/jig_igurria", domain: "", location: "",
    flag: "", },
    { name: "Fábio Henrique Cabrini", img: "https://www.fiware.org/wp-content/directories/people/images/200px/fabio-henrique-cabrini.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "Helix", "company-link": "https://gethelix.com.br/",
    content: "", linkedin: "https://www.linkedin.com/in/fabio-cabrini/", twitter: "https://twitter.com/fabiocabrini", domain: "", location: "",
    flag: "", },
    { name: "Juanjo Hierro", img: "https://www.fiware.org/wp-content/directories/people/images/200px/juanjo-hierro.jpg", position: "Chief Technology Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Juanjo Hierro (m) holds the CTO position within FIWARE Foundation where he effectively moved as full employee on January 1st, 2017. He obtained a degree in Computer Science in 1990 from the Universidad Politecnica de Madrid (UPM) and owns a certificate of research proficiency. In 1990, Juanjo joined Telefónica I+D where he stayed until he joined FIWARE Foundation. During his career at Telefónica, Juanjo had different management responsibilities in the development of mission-critical systems for Telefónica as well as several R&amp;D projects. In April 2011, he became the Chief Architect of the FIWARE programme combining this role with the one of the CTO of the IoT Division at Telefónica R&amp;D since November 2013. Besides his CTO position at FIWARE Foundation, Juanjo also plays the role of Chairman of the Technical Steering Committee which drives the technical direction of the FIWARE open source platform.", linkedin: "https://www.linkedin.com/in/jhierro/", twitter: "https://twitter.com/JuanjoHierro", domain: "", location: "",
    flag: "", },
    { name: "Gabriel Huecas", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gabriel-huecas.jpg", position: "Deputy Director", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "", linkedin: "https://www.linkedin.com/in/gabrielhuecas/", twitter: "https://twitter.com/ghuecas", domain: "", location: "",
    flag: "", },
    { name: "José Incera", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-incera.jpg", position: "Full Professor", company: "ITAM", "company-link": "https://facultad.itam.mx/en",
    content: "", linkedin: "https://www.linkedin.com/in/jincera/", twitter: "https://twitter.com/jincera", domain: "", location: "",
    flag: "", },
    { name: "Antonio Jara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonio-jara.jpg", position: "Chief Scientific Officer", company: "Hopu – Libelium", "company-link": "https://hopu.eu/",
    content: "Antonio has a PhD from the University of Murcia (Spain) and a MBA from the ENAE business school and UCAM (2012). He has received entrepreneurship awards from ENAE, emprendeGo, IPSO Alliance Award for its disruptive innovation in the IoT. As part of HOP Ubiquitous, Jara is focused on the Smart Cities market with solutions for citizens engagements, tourism, active participation, physical web and environmental monitoring (air quality sensors) in projects such as ENIAC SAFESENS, interoperability / pilots (SmartSDK, Synchronicity, Organicity, BeinCPPS) and also in several actions related to security/privacy (INPUT and FORTIKA).", linkedin: "https://www.linkedin.com/in/jara-libelium/", twitter: "https://twitter.com/antonio_jara", domain: "", location: "",
    flag: "", },
    { name: "Ziya Karakaya", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ziya-karakaya.jpg", position: "Associate Professor", company: "Atilim University", "company-link": "https://www.atilim.edu.tr/en",
    content: "", linkedin: "https://www.linkedin.com/in/ziyakarakaya/", twitter: "https://twitter.com/ziya_karakaya", domain: "", location: "",
    flag: "", },
    { name: "Filip Lemic", img: "https://www.fiware.org/wp-content/directories/people/images/200px/filip-lemic.jpg", position: "Senior Researcher", company: "i2CAT Foundation", "company-link": "https://i2cat.net/",
    content: "", linkedin: "https://www.linkedin.com/in/lemic/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Fernando López Aguilar", img: "https://www.fiware.org/wp-content/directories/people/images/200px/fernando-lopez-aguilar.jpg", position: "Cloud &amp; Platform Expert", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Fernando López de Aguilar (m) is FIWARE Cloud and Platform Senior Expert at the FIWARE Foundation. He obtained a Bachelor Degree in computer science summa cum laude by E.P.S. Córdoba and Master Degree in Computer Science from the E.T.S Ingeniería Informática - University of Málaga in 1998. In March 2000, he started working in Meta4 S.A. as a Software Engineer at R&amp;D Department as a Database Expert and Java developer. In May 2001, he joined Telefónica I+D where he participated in multiple R&amp;D project lines covering advanced broadband communications, NGN, IPv4/IPv6 compatibility, Mobile IP, multimedia applications, new mobile services, M2M communication, semantic web sensors, NoSQL DB and definition of IoT reference architecture. Since 2011 and until he joined the FIWARE Foundation.", linkedin: "https://www.linkedin.com/in/fernandolopezaguilar/", twitter: "https://twitter.com/flopezaguilar", domain: "", location: "",
    flag: "", },
    { name: "Brigitte Lutz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/brigitte-lutz.jpg", position: "Data Governance Coordinator", company: "City of Vienna", "company-link": "https://www.wien.gv.at/english/",
    content: "", linkedin: "https://www.linkedin.com/in/brigitte-lutz-52a76955/", twitter: "https://twitter.com/brigittelutz", domain: "", location: "",
    flag: "", },
    { name: "Sara Madariaga", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sara-madariaga.jpg", position: "Head of Arsys Lab", company: "Arsys", "company-link": "https://www.arsys.net/",
    content: "", linkedin: "https://www.linkedin.com/in/saramadariaga/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Lanfranco Marasso", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lanfranco-marasso.jpg", position: "Program Director", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Lanfranco has a strong managerial background with a proven track record in IT projects and innovation in public sector, as well as a good strategic vision complemented by a remarkable execution effectiveness. After completing Engineering at University of Genova, he took his Ph.D. on Process Engineering at Polytechnic of Milan. He is currently the Smart City Program Director at Engineering Ingegneria Informatica spa. He has been involved at C-level in private companies at national and international level (Boston, MA, USA). In 1999 he moved from private to public sector as CIO of Municipality of Parma (Italy), covering important role for Italian Ministries. In 2003 he went back to private sector, at Engineering covering senior positions in Public Sector Department. Since 2009 he has been working in R&amp;D Department looking at the technological transfer from Research to Innovation to the Market, mainly in public sector. He has co-founded several companies and startups (first CONTECO 1994, last beMINT 2015). He is playing an active role on several EU initiatives on Software and Services for Public Sector: FIWARE (FIWARE Smart Cities Domain Committee), ENOLL (European Network of Living Lab), BDVA (Big Data Value Association), ECSO (European Cyber Security Organisation) and AIOTI (Alliance Internet Of Thing Innovation). He has published several articles and books on process and project management, new technologies applications and innovation in public sector and smart city.", linkedin: "https://www.linkedin.com/in/marasso/", twitter: "https://twitter.com/lmarasso", domain: "", location: "",
    flag: "", },
    { name: "Jaime Martín-Sauceda Martín", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jaime-martin-sauceda.jpg", position: "Project Manager", company: "Telefónica", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/jmartin-sauceda/", twitter: "https://twitter.com/jaime_msauceda", domain: "", location: "",
    flag: "", },
    { name: "Carmen Martín Ramírez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/carmen-martin-ramirez.jpg", position: "Project Manager", company: "Telefónica", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/carmen-mart%C3%ADn-ram%C3%ADrez-a22972a/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Francisco Meléndez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francisco-melendez.jpg", position: "Technical Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Francisco Melendez (m) is a Telecommunications &amp; Robotics Engineer and is FIWARE’s Technical Expert in Robotics, Automation and Industry 4.0. He is also one of the representatives of FIWARE in the Digital Twin Consortium and some international projects where FIWARE is developing its technical roadmap in robotics and automation. As a mobile robotics engineer and researcher with more than 8 years of experience in web-enabled robot applications, his work is currently focused on the development of convenient interfaces between cyber physical systems and digital twins in FIWARE-based solutions.", linkedin: "https://www.linkedin.com/in/franmelfer/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Daniel Menchaca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/daniel-menchaca.jpg", position: "Innovation Specialist", company: "ECOEMBES", "company-link": "https://www.ecoembes.com/en",
    content: "", linkedin: "https://www.linkedin.com/in/danielmenchaca/", twitter: "https://twitter.com/danielmenchaca", domain: "", location: "",
    flag: "", },
    { name: "Theocharis Moysiadis", img: "https://www.fiware.org/wp-content/directories/people/images/200px/theocharis-moysiadis.jpg", position: "Business Development Manager", company: "Future Intelligence", "company-link": "https://www.f-in.gr/",
    content: "", linkedin: "https://www.linkedin.com/in/theocharis-moysiadis-63583a1a/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Francisco Javier Peralta López", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francisco-javier-peralta-lopez.jpg", position: "Project Manager", company: "Telefónica", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/fjperalta/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Joaquín Salvachúa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/joaquin-salvachua.jpg", position: "Associate Professor", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "Prof. Joaquín Salvachúa received a master degree in Computer Science. He holds the Orange Chair for the “Science of Complex Networks” and the Kairos Chair on “Bank Middleware and Blockchain” at UPM and is a member of the UPM-ING and CyberAula groups. He has participated in several European research projects with several publications at international magazines, books and conferences. (https://orcid.org/0000-0002-7269-8079). Also have participated in several standardization activities, including been coauthor one RFC ( RFC 8802 ).His research focuses today on WebRTC, Cloud infrastructure, social graphs and recommendation, agile cloud infrastructures, P2P, DHT (Distributed HashTables), IOT, Non SQL Data Bases, Big data processing architectures, Identity Management and BlockChain distributed agreement algorithms.His teaching duties includes cloud computing, distributed application development, Databases, Web Full-stack development, Blockchain architecture, Data Engineering and Big data architecture and applications. Has been involved in the FIWARE Initiative since it started (2010) and he is architect and developer of several GE related to security, data persistence and Big Data analysis.", linkedin: "https://es.linkedin.com/in/jsalvachua", twitter: "https://twitter.com/jsalvachua", domain: "", location: "",
    flag: "", },
    { name: "Antonio Sanchez Pineda", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "Founder &amp; Chief Executive Officer", company: "Hearing Software", "company-link": "https://byhs.eu/",
    content: "", linkedin: "https://www.linkedin.com/in/antoniosanchezpineda/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "David Seoane", img: "https://www.fiware.org/wp-content/directories/people/images/200px/david-seoane.jpg", position: "Head of Communities", company: "FundingBox", "company-link": "https://fundingbox.com/",
    content: "Over 12 years of experience in Fundraising in EU programs, Since, 2020, responsible for the Community Building Strategy across all European and private projects managed by FundingBox, curating the FundingBox Spaces database (+45k users).", linkedin: "https://www.linkedin.com/in/davidseoane/", twitter: "https://twitter.com/davidseoanevila", domain: "", location: "",
    flag: "", },
    { name: "Satinder Jeet Singh", img: "https://www.fiware.org/wp-content/directories/people/images/200px/satinder-jeet-singh.jpg", position: "Associate General Manager", company: "NEC Corporation India", "company-link": "https://in.nec.com/",
    content: "", linkedin: "https://www.linkedin.com/in/satinder-jeet-singh-a217587/", twitter: "https://twitter.com/satinderjs", domain: "", location: "",
    flag: "", },
    { name: "Enrico Sodacci", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "Senior Developer", company: "Agricolus", "company-link": "https://www.agricolus.com/",
    content: "", linkedin: "https://www.linkedin.com/in/enrico-sodacci-80793031/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Kazuhito Suda", img: "https://www.fiware.org/wp-content/directories/people/images/200px/kazuhito-suda.jpg", position: "Senior Developer", company: "FIWARE", "company-link": "https://www.fiware.org",
    content: "", linkedin: "", twitter: "https://twitter.com/kz_suda", domain: "", location: "",
    flag: "", },
    { name: "Ousmane Thiare", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "Associate Professor", company: "University Gaston Berger", "company-link": "https://www.ugb.sn/",
    content: "", linkedin: "https://www.linkedin.com/in/ousmane-thiare-11b5bb27/", twitter: "", domain: "", location: "",
    flag: "", },
    { name: "Rahul Tomar", img: "https://www.fiware.org/wp-content/directories/people/images/200px/rahul-tomar.jpg", position: "Co-Founder", company: "DigitalTwin Technology", "company-link": "https://www.digitaltwin.technology/",
    content: "", linkedin: "https://www.linkedin.com/in/rahultomarpmp/", twitter: "https://twitter.com/rahul_606", domain: "", location: "",
    flag: "", },
    { name: "Ken Zangelin", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ken-zangelin.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "", linkedin: "https://www.linkedin.com/in/kzangeli/", twitter: "", domain: "", location: "",
    flag: "", },
];