var companies = [
        'Adani',
        'African Smart Territories',
        'Agricolus',
        'Arsys',
        'Atilim University',
        'AUSTRALO',
        'bee smart city GmbH',
        'Berlin Thinking Consulting',
        'BluSky Consulting',
        'City of Herne',
        'City of Vienna',
        'Cubilock',
        'DigitalTwin Technology',
        'ECOEMBES',
        'Engineering',
        'EPPO',
        'Faubourg Numérique',
        'FIWARE',
        'FIWARE Digital Transformation Lab at the University of Córdoba',
        'FIWARE Foundation',
        'FIWARE Space',
        'FundingBox',
        'Future Intelligence',
        'GaiaX',
        'Hochschule Bochum',
        'Huawei R&amp;D',
        'i2CAT Foundation',
        'IMD/UFRN',
        'Innovalia',
        'IOTA Foundation',
        'iP-NETs',
        'ITAM',
        'JIG',
        'Latitudo 40',
        'Libelium',
        'Martel Innovation',
        'Meditech Competence Center',
        'MNX Online',
        'ms.GIS',
        'NEC Corporation',
        'NEC Corporation India',
        'Nivid Technologies',
        'Open Solutions For Government',
        'Polytechnic School of the University of São Paulo',
        'Poznan Supercomputing and Networking Center',
        'Red Hat',
        'Secmotic',
        'TeamDev',
        'TeamDev SRL',
        'Telefónica',
        'ThoughtLab',
        'ThoughtLab Group',
        'Universidad Politécnica de Madrid',
        'Vienna Business Agency',
        'WOBCOM',
]; var departments = [
]; var domains = [
]; var titles = [
        'Assistant Professor',
        'Associate General Manager',
        'Business Development Manager',
        'CDO',
        'CDTO',
        'CEO',
        'Chief Architect',
        'Cloud Expert',
        'Co-Founder',
        'Community Architect',
        'Consultant',
        'COO',
        'Coordinator',
        'CSO',
        'CTO',
        'Deputy Director',
        'Developer',
        'Director',
        'Evangelist',
        'Expert',
        'FIWARE Manager',
        'Head of Communities',
        'Innovation Specialist',
        'Manager',
        'ML Specialist',
        'Platform Expert',
        'President',
        'Product Manager',
        'Professor',
        'Project Manager',
        'Researcher',
        'Software Architect',
        'Solution Architect',
        'Technical Expert',
]; var countries = [
]; var modalData = [
    { name: "Abhinav Praween Agrawal", img: "https://www.fiware.org/wp-content/directories/people/images/200px/abhinav-praween-agrawal.jpg", position: "Chief Architect", company: "Adani", "company-link": "https://www.adani.com/",
    content: "", linkedin: "https://www.linkedin.com/in/abhitechie/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Ulrich Ahle", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ulrich-ahle.jpg", position: "Chief Executive Officer", company: "GaiaX", "company-link": "https://gaia-x.eu/",
    content: "Ulrich is a reputed executive in the IT sector, formerly Vice President and leader of the Manufacturing and Industrie 4.0 System Integration business at Atos in Germany. He is also founder and member of the Board of the International Data Spaces Association in Germany and served 16 years in the Board of the prostep IVIP organization until April 2018. After an apprenticeship as toolmaker at Hella KG, he studied Mechanical Engineering at the University of Paderborn. In his career, Ahle held several positions as development engineer, Director of PLM services, sales director and Vice President. He has been part of Nixdorf Computer AG, Siemens and Atos. From January 2017 until the end of 2023 Ulrich Ahle was Chief Executive Officer of the FIWARE Foundation headquartered in Berlin, Germany. Starting from November 2023 Ulrich became CEO of the Gaia-X Association headquartered in Brussels, Belgium.", linkedin: "https://www.linkedin.com/in/ulrichahle", twitter: "https://twitter.com/UlrichAhle", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Dr. Álvaro Alonso", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alvaro-alonso.jpg", position: "Assistant Professor", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "Álvaro Alonso is currently an Assistant Professor with the UPM. His research interests include Multi Video Conferencing Systems, Security Management in Smart Context scenarios, and Public Open Data.", linkedin: "https://www.linkedin.com/in/alvaroalonsogonzalez", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Joseph Appleton", img: "https://www.fiware.org/wp-content/directories/people/images/200px/joseph-appleton.jpg", position: "Editorial Director", company: "bee smart city GmbH", "company-link": "https://beesmart.city",
    content: "Over the past few years, I have had the pleasure of working with former FIWARE CEO Ulrich Ahle. I was instrumental inviting Ulrich to Central Eastern Europe to plant the seed of FIWARE into the minds of organisations and governments in Poland. I have also worked closely with FIWARE&#x27;s communication department, working together on publications, shared content, and press releases. As a guest at the FIWARE Global Summit in Vienna in 2023, I was able to network with other FIWARE members and develop strong business relationships with key figures from Amazon Web Services, Atos, Red Hat, DKSR, and many more. Thanks to my position as an &quot;unofficial&quot; FIWARE member, I have been able to view the Foundation from an outsider&#x27;s perspective and develop my own positive opinions about the organisation and everything that it stands for. I hope to spread the FIWARE gospel for many years to come and preach the importance of open source, open standards, interoperability, and the necessity of breaking silos for the greater good of the urban community.", linkedin: "https://www.linkedin.com/in/joe-appleton1/", twitter: "https://twitter.com/JoeAppleton19", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Dario Avallone", img: "https://www.fiware.org/wp-content/directories/people/images/200px/dario-avallone.jpg", position: "Independent consultant", company: "", "company-link": "",
    content: "I have been engaged in FIWARE since day 1 being a founder of the FOUNDATION and even before. I have contunously contributes to the growth of the Foudaion as Board Member and Chairman of the Board and to position FIWARE as a central component for the development of Data Economy in Europe.", linkedin: "https://www.linkedin.com/in/dario-avallone-428934a/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Prof. Thais Batista", img: "https://www.fiware.org/wp-content/directories/people/images/200px/thais-batista.jpg", position: "Professor", company: "Innovalia", "company-link": "https://www.ufrn.br/en",
    content: "", linkedin: "https://www.linkedin.com/in/thais-batista-58b9b94a/", twitter: "https://twitter.com/thaisvbatista", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Ali Benbrahim", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ali-benbrahim.jpg", position: "Chief Executive Officer", company: "iP-NETs", "company-link": "http://www.ipnets.tn/",
    content: "", linkedin: "https://www.linkedin.com/in/ali-benbrahim-71203121/", twitter: "https://twitter.com/alibb0404", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Salim Bendris", img: "https://www.fiware.org/wp-content/directories/people/images/200px/salim-bendris.jpg", position: "Executive Vice President Global Sales", company: "Nivid Technologies", "company-link": "https://nividit.com",
    content: "I whole heartedly endorse the technology and its advantages, with a strong emphasis on how FIWARE&#x27;s open standards offer broader options for clients. I am confident in my ability to make a meaningful influence and impact.", linkedin: "https://www.linkedin.com/in/salim-bendris-2693129/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "José Benitez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-benitez.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "Secmotic", "company-link": "https://secmotic.com/",
    content: "", linkedin: "https://www.linkedin.com/in/jose-benitez-secmotic", twitter: "https://twitter.com/josesecmotic", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Alexander Berlin", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alexander-berlin.jpg", position: "Chief Executive Officer", company: "Berlin Thinking Consulting", "company-link": "www.berlin-thinking.com",
    content: "", linkedin: "https://www.linkedin.com/in/alexanderberlin/?originalSubdomain&#x3D;de", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Marivi Briz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/maria-virtudes-briz.jpg", position: "Head Of Product Management", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/mariavirtudesbriz/", twitter: "https://twitter.com/marivibriz", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "José Manuel Cabello", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-manuel-cabello.jpg", position: "R&amp;D Director", company: "Innovalia", "company-link": "https://innovalia.org/en/",
    content: "", linkedin: "https://www.linkedin.com/in/jos%C3%A9-manuel-cabello-montesino-2936a479/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "José Manuel Cantera Fonseca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-manuel-cantera-fonseca.jpg", position: "Software Architect", company: "IOTA Foundation", "company-link": "https://www.iota.org/",
    content: "", linkedin: "https://www.linkedin.com/in/jmcanterafonseca/", twitter: "https://twitter.com/jmcantera", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Javier Carpintero Ordoñez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/javier-carpintero-ordonez.jpg", position: "Smartcities, IoT &amp; Industry 4.0 Manager", company: "NEC Corporation", "company-link": "https://www.nec.com/",
    content: "", linkedin: "https://www.linkedin.com/in/jacarpint/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Lou Celi", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lou-celi.jpg", position: "CEO", company: "ThoughtLab", "company-link": "https://www.thoughtlabgroup.com",
    content: "I have worked with FIWARE for the last five years. ThoughtLab is a global research firms that specializes on the impact of technology on government and business. Every 18 months, we conduct a major benchmarking study on how cities around the world use technology and innovative solutions to drive their future. We have a relationship with FIWARE where we but provide advice, contacts, and research to one another. With my company based in the US, we have the capabilities to help FIWARE expand in this part of the world.", linkedin: "https://www.linkedin.com/in/louceli/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Chandra Challagonda", img: "https://www.fiware.org/wp-content/directories/people/images/200px/chandra-challagonda.jpg", position: "Solution Architect", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Chandra Challagonda (m) is Senior Architect at FIWARE Foundation in Germany. Chandra holds a Masters in Software Engineering degree from 1999 - 2002. Chandra comes with nearly 25 years of experience in software development, integration projects and software product management. He worked for Ericsson and Nokia in various technical and non-technical roles in Network infrastructure and smartphones for 15 years. Chandra has been an active member of the FIWARE community since 2015 and joined FIWARE Foundation in 2019. In FIWARE Foundation, Chandra is the platform architect for SmartMaaS and IMPRESS projects funded by the German Federal government. Before joining FIWARE Foundation, he was part of the team which created a digital twin for Helsinki Transportation.", linkedin: "https://linkedin.com/in/challagonda", twitter: "https://twitter.com/challagonda", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Josė Checa Claudel", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-checa-claudel.jpg", position: "Coordinator of FiWare Digital Transformation Lab at the University of Córdoba", company: "FIWARE Digital Transformation Lab at the University of Córdoba", "company-link": "https://www.uco.es/atdfiware/",
    content: "I have been disseminating FIWARE technology within the university community, local administrations and research projects for more than four years. I believe that we are one of the Universities that has the most movement disseminating this technology in Spain, especially in the agri-food environment and smart cities.", linkedin: "https://www.linkedin.com/in/jcheca", twitter: "https://twitter.com/abbasben", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Andrea Chiancone", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-chiancone.jpg", position: "Product Manager", company: "Agricolus", "company-link": "https://www.agricolus.com/",
    content: "", linkedin: "https://www.linkedin.com/in/andrea-chiancone-a3495a5/", twitter: "https://twitter.com/Antonio_Jara", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Giovanni Coppa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/giovanni-coppa.jpg", position: "Coordinator Astrid iHub", company: "WOBCOM", "company-link": "https://www.wobcom.de/",
    content: "More than 10 years of experience in Data Center and digital transformation. I am passionate about energy efficiency and environmental friendly technologies, with a strong interest in digital revolution and strategic innovation.", linkedin: "https://www.linkedin.com/in/giovannicoppa/", twitter: "https://twitter.com/korematic", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Andrea Cruciani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/andrea-cruciani.jpg", position: "Co-Founder &amp; Chief Executive Officer", company: "TeamDev", "company-link": "https://www.teamdev.it/en/",
    content: "Andrea is the Agricolus co-founder and CEO, member of FIWARE Foundation BoD, Chairman of the FIWARE Smart AgriFood MSC. He runs the international business area and the financial aspects of the company and he has a technical background and experience in applications Development, Enterprise Architectures, Cloud Computing, and GIS. Andrea is involved in Innovative Startup Evolution and scaleup, during the years he worked with Public Administration, multinational companies, NGOs, and SMEs. He is a speaker for several universities and public events where he is invited to discuss entrepreneurship and digital transformation, and he is a contributor in several technical articles and publications about agritech.", linkedin: "https://www.linkedin.com/in/andreacruciani/", twitter: "https://twitter.com/kokkete", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Roi Rodriguez De Bernardo", img: "https://www.fiware.org/wp-content/directories/people/images/200px/roi-rodriguez-de-bernardo.jpg", position: "Director of AI &amp; Cloud Ecosystem", company: "Huawei R&amp;D", "company-link": "https://www.huawei.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/roirodriguezdebernardo/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Gabriele De Luca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gabriele-de-luca.jpg", position: "Senior Researcher", company: "Engineering", "company-link": "https://www.eng.it/en/",
    content: "Gabriele De Luca graduated as Doctor with Laude in Computer Engineering from the University of Salento. He has been working in the R&amp;D Lab for Engineering Ingegneria Informatica S.p.A. since 2014 as part of the “Digital Industry and Agrifood” Unit. He has been involved in different Italian and European research projects playing several roles, such as software developer, solution designer, system architect and information expert. Currently, he acts as Technology Manager and Team Leader. The main application fields are Advanced Manufacturing, Smart Farming, Supply Chain Management, Operational Intelligence, Artificial Intelligence, Internet of Things and Food Safety whereas the main activities are correlated to Event Processing, Sensor Data Processing (OGC standards such as Sensor Web Enablement), Decision Support Systems, Internet of Things (mainly in the FIWARE context), Data Sovereignty and Data Spaces (IDSA-based). His relevant expertise and experiences include Architecture Design, System Integration, and Collaborative Working Environment, from both software engineering and technological points of view. Main research fields are applied to Digital Industry, including Operational Intelligence (especially in Complex Event Processing and Process Mining), Supply Chain Integration, and so on.", linkedin: "https://www.linkedin.com/in/gabriele-de-luca-b4132861/", twitter: "https://twitter.com/gabrielede_luca", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Stefano De Panfilis", img: "https://www.fiware.org/wp-content/directories/people/images/200px/stefano-depanfilis.jpg", position: "Chief Operations Officer", company: "FIWARE Foundation e.V.", "company-link": "https://www.fiware.org/",
    content: "Stefano de Panfilis (m) is the Chief Operating Officer at FIWARE Foundation. He graduated cum laude in Mathematics at the University of Rome “La Sapienza”. In 1984, he was hired in Engineering Ingegneria Informatica S.P.A as a software engineer. In 1986, he became Project Manager to then move to the R&amp;D department managing the “Formal Methods” unit. In 1993, he supported Engineering to receive the ISO-9001 compliancy. From 1994, he was involved in European R&amp;D. He coordinated SeCSE (IST 6FP), aiming at implement a platform for Service-Centric Systems Engineering, CBSEnet (IST-5FP NoE), CLARiFi (IST 5FP), DOOR (ESPRIT 4FP), SQUAD (INCO-DC), and VALSE (TV&amp;TT) projects, and the ENG- SODEPRO, DECO’ and DOMINARE ESSI Process Improvement Experiments. He also coordinated QualiPSo (IST 6FP) aiming at leverage Open Source Software development to recognised industrial standards, leading a consortium of 20 partners from Europe, Brazil and China. He actively participated to create and set-up the NESSI ETP of which he is the Coordinator of the Strategic Research Agenda Committee. Since 2017, he is employed by FIWARE Foundation as Chief Operations Officer.", linkedin: "https://www.linkedin.com/in/stefano-de-panfilis-1928a11/", twitter: "https://twitter.com/depa01", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Cara Delia", img: "https://www.fiware.org/wp-content/directories/people/images/200px/cara-delia.jpg", position: "Principal Community Architect", company: "Red Hat", "company-link": "https://www.redhat.com/en",
    content: "", linkedin: "https://www.linkedin.com/in/caradelia/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Vincent Demortier", img: "https://www.fiware.org/wp-content/directories/people/images/200px/vincent-demortier.jpg", position: "President", company: "Faubourg Numérique", "company-link": "http://faubourgnumerique.com/",
    content: "Vincent has multiple professional experiences in developing and deploying digital solutions: originally in industrial logistics within the automotive industry and in the food &amp; beverage industry, then as consultant for a wide variety of SMEs and finally as entrepreneur involved in the creation of new businesses. In order to contribute to the development of its regional innovative ecosystem to support the digital transition and innovation, in 2014, Vincent co-founded the association Faubourg Numérique, of which he is now president. With this entrepreneurial impulse, Faubourg Numérique is committed to the FIWARE initiative as an Innovation Hub and involved in the future EDIH Sumity. Vincent is a certified FIWARE expert, i4Trust LEBD, and DIH2 LER.", linkedin: "https://www.linkedin.com/in/vincent-demortier-fr/", twitter: "https://twitter.com/VincDemortier", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Bhushan", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "IT Admin", company: "Cubilock", "company-link": "https://cubilock.com/",
    content: "I&#x27;m an IT Admin with a passion for navigating the intricate landscape of technology. Specializing in what is kiosk mode and MDM geofencing setups, I thrive on crafting seamless user experiences. My expertise extends to MDM migration, ensuring a smooth transition for efficient device management. With a keen eye for detail, I excel in implementing kiosk browser lockdown mode, guaranteeing a secure and controlled environment. Whether troubleshooting tech hiccups or orchestrating intricate migrations, I bring a blend of precision and innovation to the realm of IT administration. Committed to staying at the forefront of advancements, I&#x27;m your go-to professional for a tech-savvy future.", linkedin: "", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Gianluca Dianese", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gianluca-dianese.jpg", position: "Digital Transformation Officer", company: "EPPO", "company-link": "https://www.eppo.europa.eu/en",
    content: "", linkedin: "https://www.linkedin.com/in/gianlucadianese/", twitter: "https://twitter.com/gdianese", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Daniele Diodati", img: "https://www.fiware.org/wp-content/directories/people/images/200px/daniele-diodati.jpg", position: "ML Specialist", company: "TeamDev", "company-link": "https://www.teamdev.it/en/",
    content: "", linkedin: "https://www.linkedin.com/in/daniele-diodati/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Gonzalo Ezquerro Martínez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gonzalo-ezquerro-martinez.jpg", position: "Chief Technology Officer", company: "JIG", "company-link": "https://www.jig.es/",
    content: "", linkedin: "https://www.linkedin.com/in/gonzalo-ezquerro-mart%C3%ADnez-94818089/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Federico Facca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/federico-facca.jpg", position: "Chief Technology Officer", company: "Martel Innovation", "company-link": "https://www.martel-innovate.com/",
    content: "Federico is the CTO of Martel, leading internal IT projects and acting as strategic lead consultant to customers, including the European Commission. Federico’s current core project is Orchestra Cities, a modular and flexible cloud-native IoT platform (mostly used in the Smart City domain). He has an extensive experience on Cloud-Native architectures, Infrastructure as a Code approach, continuous testing and monitoring to ensure infrastructure reliability. He is a strong advocate of Open Source and thrive to use and contribute to Open Source solutions. In his career he lead different large R&amp;D projects, ranging from industrial systems integration to data center deployment and federation. Before joining Martel Innovate, Federico has been area head in different FBK-CREATE-NET and STI Innsbruck. He holds a PhD and MSc in Computer Science.", linkedin: "https://www.linkedin.com/in/federicofacca/", twitter: "https://twitter.com/chicco785", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Tony Fortenberry", img: "https://www.fiware.org/wp-content/directories/people/images/200px/tony-fortenberry.jpg", position: "Executive Director", company: "Open Solutions For Government", "company-link": "https://ogov.org",
    content: "Chairman and Executive Director at Open Solutions For Government, a California nonprofit organization hosting the Open Innovation Hub, which is a new iHub showcasing FIWARE and GAIA-X compatible solutions. Former FIWARE Foundation Board Member, public sector strategist at Red Hat, Career Executive Appointee at California Health And Human Services Agency, and CIO at City of Northglenn Colorado. Decades-long advocate for the development of free/libre solutions in public sector organizations. Contributor to the Free Software Foundation and related nonprofit organizations.", linkedin: "https://www.linkedin.com/in/tonyfortenberry/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Jason Fox", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jason-fox.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation e.V.", "company-link": "https://www.fiware.org/",
    content: "Jason Fox (m) has been working for FIWARE Foundation for the last five years in the role of technical evangelist, educating and diseminating information about NGSI interfaces, JSON-LD, Linked Data, the components within the FIWARE Catalogue and Securing FIWARE architectures. Before joining FIWARE, he worked as a software engineer for over 20 years in various roles both in Germany and the United Kingdom using a wide variety of programming languages ranging from C++ to Java to Node.js. This has included coding the software behind selling lottery tickets online for the British National Lottery, and and developing and maintaining technical documentation applications for Nokia.", linkedin: "https://www.linkedin.com/in/jason-fox-8a79563/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Juan Marcelo Gaitan Leiva", img: "https://www.fiware.org/wp-content/directories/people/images/200px/juan-marcelo-gaitan-leiva.jpg", position: "FIWARE Manager", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/juanmarcelogaitan/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Fermín Galán Márquez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/fermin-galan-marquez.jpg", position: "Expert", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/fermingalan/", twitter: "https://twitter.com/ermingalan", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Pierre Golz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/pierre-golz.jpg", position: "Chief Digital Officer", company: "City of Herne", "company-link": "https://www.herne.de/",
    content: "After getting his diploma as a public administration specialist, Pierre joined the city as an organizational developer and change manager. Since 2013, he has been working on projects focused on digitization and process management, and, at the age of 31, Pierre is the city’s youngest CDO to date. Pierre is also a lecturer in E-Government, Digitization, and Knowledge Management (among other areas) and feels that being able to combine science, economy and public management adds considerably to his career and role within the city.", linkedin: "https://www.linkedin.com/in/pierre-golz-311396156/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Jose Gonzalez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-gonzalez.jpg", position: "Chief Executive Officer", company: "AUSTRALO", "company-link": "https://www.australo.org/",
    content: "", linkedin: "https://www.linkedin.com/in/joseglezes/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Ignacio Gurría de la Torre", img: "https://www.fiware.org/wp-content/directories/people/images/200px/javier-gurria.jpg", position: "Chief Executive Officer", company: "JIG", "company-link": "https://www.jig.es/",
    content: "", linkedin: "https://www.linkedin.com/in/ignaciog3/", twitter: "https://twitter.com/jig_igurria", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Fábio Henrique Cabrini", img: "https://www.fiware.org/wp-content/directories/people/images/200px/fabio-henrique-cabrini.jpg", position: "Researcher", company: "Polytechnic School of the University of São Paulo", "company-link": "https://www.pad.lsi.usp.br",
    content: "", linkedin: "https://www.linkedin.com/in/fabio-cabrini/", twitter: "https://twitter.com/fabiocabrini", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Juanjo Hierro", img: "https://www.fiware.org/wp-content/directories/people/images/200px/juanjo-hierro.jpg", position: "", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "Juanjo Hierro (m) obtained a degree in Computer Science in 1990 from the Universidad Politecnica de Madrid (UPM) and owns a certificate of research proficiency. In 1990, Juanjo joined Telefónica I+D where he stayed until he joined FIWARE Foundation. During his career at Telefónica, Juanjo had different management responsibilities in the development of mission-critical systems for Telefónica as well as several R&amp;D projects. In April 2011, he became the Chief Architect of the FIWARE programme combining this role with the one of the CTO of the IoT Division at Telefónica R&amp;D since November 2013. Juanjo plays the role of Chairman of the Technical Steering Committee which drives the technical direction of the FIWARE open source platform.", linkedin: "https://www.linkedin.com/in/jhierro/", twitter: "https://twitter.com/JuanjoHierro", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Gabriel Huecas", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gabriel-huecas.jpg", position: "Deputy Director", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "", linkedin: "https://www.linkedin.com/in/gabrielhuecas/", twitter: "https://twitter.com/ghuecas", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Prof. José Incera", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jose-incera.jpg", position: "Professor", company: "ITAM", "company-link": "https://facultad.itam.mx/en",
    content: "", linkedin: "https://www.linkedin.com/in/jincera/", twitter: "https://twitter.com/jincera", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Antonio Jara", img: "https://www.fiware.org/wp-content/directories/people/images/200px/antonio-jara.jpg", position: "Chief Scientific Officer", company: "Libelium", "company-link": "https://www.libelium.com/",
    content: "Antonio has a PhD from the University of Murcia (Spain) and a MBA from the ENAE business school and UCAM (2012). He has received entrepreneurship awards from ENAE, emprendeGo, IPSO Alliance Award for its disruptive innovation in the IoT. As part of HOP Ubiquitous, Jara is focused on the Smart Cities market with solutions for citizens engagements, tourism, active participation, physical web and environmental monitoring (air quality sensors) in projects such as ENIAC SAFESENS, interoperability / pilots (SmartSDK, Synchronicity, Organicity, BeinCPPS) and also in several actions related to security/privacy (INPUT and FORTIKA).", linkedin: "https://www.linkedin.com/in/jara-libelium/", twitter: "https://twitter.com/antonio_jara", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Prof. Ziya Karakaya", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ziya-karakaya.jpg", position: "Professor", company: "Atilim University", "company-link": "https://www.atilim.edu.tr/en",
    content: "", linkedin: "https://www.linkedin.com/in/ziyakarakaya/", twitter: "https://twitter.com/ziya_karakaya", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Lukas Künzel", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lukas-kuenzel.jpg", position: "Chief Technology Officer", company: "ms.GIS", "company-link": "https://www.msgis.com/",
    content: "Lukas Künzel (m) after studying computer science and geographic information science started at young age as a software developer and had the chance to continuously challenge myself at ms.GIS by getting more responsibility, manage country wide software projects and lead a team of software and data engineers. For the last couple of years I was CTO overseeing all activities related to technology and data. Currently I am leading our management team as an Integrator, following the approach of entrepreneur operating system.", linkedin: "https://www.linkedin.com/in/lukas-k%C3%BCnzel-825033155/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Filip Lemic", img: "https://www.fiware.org/wp-content/directories/people/images/200px/filip-lemic.jpg", position: "Senior Researcher", company: "i2CAT Foundation", "company-link": "https://i2cat.net/",
    content: "", linkedin: "https://www.linkedin.com/in/lemic/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Prof. Frederico Lopes", img: "https://www.fiware.org/wp-content/directories/people/images/200px/frederico-lopez.jpg", position: "Professor", company: "IMD/UFRN", "company-link": "https://sigaa.ufrn.br/sigaa/public/docente/portal.jsf?siape&#x3D;2510306",
    content: "", linkedin: "https://www.linkedin.com/in/fredericoemanuel?miniProfileUrn&#x3D;urn%3Ali%3Afs_miniProfile%3AACoAACaBf3QBZe0Y-SyN13hRuqa4CzhPQED5YOw&amp;lipi&#x3D;urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3BHJaPif%2B%2FTPOgurapCbv9yw%3D%3D", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Fernando López Aguilar", img: "https://www.fiware.org/wp-content/directories/people/images/200px/fernando-lopez-aguilar.jpg", position: "Cloud &amp; Platform Expert", company: "FIWARE Foundation e.V.", "company-link": "https://www.fiware.org/",
    content: "Fernando López de Aguilar (m) is FIWARE Cloud and Platform Senior Expert at the FIWARE Foundation. He obtained a Bachelor Degree in computer science summa cum laude by E.P.S. Córdoba and Master Degree in Computer Science from the E.T.S Ingeniería Informática - University of Málaga in 1998. In March 2000, he started working in Meta4 S.A. as a Software Engineer at R&amp;D Department as a Database Expert and Java developer. In May 2001, he joined Telefónica I+D where he participated in multiple R&amp;D project lines covering advanced broadband communications, NGN, IPv4/IPv6 compatibility, Mobile IP, multimedia applications, new mobile services, M2M communication, semantic web sensors, NoSQL DB and definition of IoT reference architecture. Since 2011 and until he joined the FIWARE Foundation.", linkedin: "https://www.linkedin.com/in/fernandolopezaguilar/", twitter: "https://twitter.com/flopezaguilar", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Miguel López Corbacho", img: "https://www.fiware.org/wp-content/directories/people/images/200px/miguel-lopez-corbacho.jpg", position: "Consultant", company: "FIWARE Space", "company-link": "https://fiware.space/",
    content: "Miguel López Corbacho is a facilitator at the FIWARE Space Premium FIWARE iHub. He has participated in several international events (including IOTSWC, SCEWC, and 2022 FIWARE Global Summit). In addition, he runs weekly training events on FIWARE technologies; and he is in contact with the local, regional and national innovation and entrepreneurial ecosystem, with a view to helping companies and administrations adopt FIWARE Standards. In this regard, it’s worth noting that six different products in the FIWARE Marketplace applied there after participating in our Mentorship Programme.", linkedin: "https://www.linkedin.com/in/miguellcorb/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Brigitte Lutz", img: "https://www.fiware.org/wp-content/directories/people/images/200px/brigitte-lutz.jpg", position: "Data Governance Coordinator", company: "City of Vienna", "company-link": "https://www.wien.gv.at/english/",
    content: "", linkedin: "https://www.linkedin.com/in/brigitte-lutz-52a76955/", twitter: "https://twitter.com/brigittelutz", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Sara Madariaga", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sara-madariaga.jpg", position: "Head of Arsys Lab", company: "Arsys", "company-link": "https://www.arsys.net/",
    content: "", linkedin: "https://www.linkedin.com/in/saramadariaga/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Mannix Manglani", img: "https://www.fiware.org/wp-content/directories/people/images/200px/mannix-manglani.jpg", position: "General Manager", company: "MNX Online", "company-link": "https://www.mnxonline.com",
    content: "", linkedin: "https://www.linkedin.com/in/mannixmanglani?miniProfileUrn&#x3D;urn%3Ali%3Afs_miniProfile%3AACoAAAZMFDgBjmMekjOkBaIEPstVs6l5OseqtZo&amp;lipi&#x3D;urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3By8qYaUPoSniYqtlwN6E%2BMQ%3D%3D", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Lanfranco Marasso", img: "https://www.fiware.org/wp-content/directories/people/images/200px/lanfranco-marasso.jpg", position: "Program Director", company: "Engineering S.p.A.", "company-link": "https://www.eng.it/en/",
    content: "Lanfranco has a strong managerial background with a proven track record in IT projects and innovation in public sector, as well as a good strategic vision complemented by a remarkable execution effectiveness. After completing Engineering at University of Genova, he took his Ph.D. on Process Engineering at Polytechnic of Milan. He is currently the Smart City Program Director at Engineering Ingegneria Informatica spa. He has been involved at C-level in private companies at national and international level (Boston, MA, USA). In 1999 he moved from private to public sector as CIO of Municipality of Parma (Italy), covering important role for Italian Ministries. In 2003 he went back to private sector, at Engineering covering senior positions in Public Sector Department. Since 2009 he has been working in R&amp;D Department looking at the technological transfer from Research to Innovation to the Market, mainly in public sector. He has co-founded several companies and startups (first CONTECO 1994, last beMINT 2015). He is playing an active role on several EU initiatives on Software and Services for Public Sector: FIWARE (FIWARE Smart Cities Domain Committee), ENOLL (European Network of Living Lab), BDVA (Big Data Value Association), ECSO (European Cyber Security Organisation) and AIOTI (Alliance Internet Of Thing Innovation). He has published several articles and books on process and project management, new technologies applications and innovation in public sector and smart city.", linkedin: "https://www.linkedin.com/in/marasso/", twitter: "https://twitter.com/lmarasso", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Jaime Martín-Sauceda Martín", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jaime-martin-sauceda.jpg", position: "Project Manager", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/jmartin-sauceda/", twitter: "https://twitter.com/jaime_msauceda", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Carmen Martín Ramírez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/carmen-martin-ramirez.jpg", position: "Project Manager", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/carmen-mart%C3%ADn-ram%C3%ADrez-a22972a/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Prof. Haydar Mecit", img: "https://www.fiware.org/wp-content/directories/people/images/200px/haydar-mecit.jpg", position: "Professor", company: "Hochschule Bochum", "company-link": "https://www.hochschule-bochum.de/",
    content: "Haydar was appointed to Bochum University of Applied Sciences in 2019 as part of an endowed professorship by the local utility Stadtwerke Herne AG. In the Department of Electrical Engineering and Computer Science his research area Urban Energy and Mobility Systems deals with R&amp;D on smart city solutions. His research focuses on the integration of IoT sensor technologies and IT platforms in real-world laboratories in urban areas whereas application areas are related to smart energy, environment and mobility. Previously, Haydar worked as a senior expert in a central R&amp;D department of the utility innogy SE, now a division of E.ON SE on topics related to electric mobility and data driven business models. Between 2005 and 2017 he worked in various business areas of the technology company thyssenkrupp AG, most recently as a senior engineer R&amp;D in an innovation department in the areas of mobility, energy and infrastructure. In addition, he is also a member of the FIWARE Foundation’s Smart Energy Mission Support Committee.", linkedin: "https://www.linkedin.com/in/haydarmecit/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Francisco Meléndez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francisco-melendez.jpg", position: "Technical Expert &amp; Evangelist", company: "FIWARE Foundation e.V.", "company-link": "https://www.fiware.org/",
    content: "Francisco Melendez (m) is a Telecommunications &amp; Robotics Engineer and is FIWARE’s Technical Expert in Robotics, Automation and Industry 4.0. He is also one of the representatives of FIWARE in the Digital Twin Consortium and some international projects where FIWARE is developing its technical roadmap in robotics and automation. As a mobile robotics engineer and researcher with more than 8 years of experience in web-enabled robot applications, his work is currently focused on the development of convenient interfaces between cyber physical systems and digital twins in FIWARE-based solutions.", linkedin: "https://www.linkedin.com/in/franmelfer/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Daniel Menchaca", img: "https://www.fiware.org/wp-content/directories/people/images/200px/daniel-menchaca.jpg", position: "Innovation Specialist", company: "ECOEMBES", "company-link": "https://www.ecoembes.com/en",
    content: "", linkedin: "https://www.linkedin.com/in/danielmenchaca/", twitter: "https://twitter.com/danielmenchaca", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Theocharis Moysiadis", img: "https://www.fiware.org/wp-content/directories/people/images/200px/theocharis-moysiadis.jpg", position: "Business Development Manager", company: "Future Intelligence", "company-link": "https://www.f-in.gr/",
    content: "", linkedin: "https://www.linkedin.com/in/theocharis-moysiadis-63583a1a/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Jorge Osuna Pons", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jorge-osuna-pons.jpg", position: "FIWARE Expert", company: "FIWARE Space", "company-link": "https://fiware.space/en/",
    content: "Jorge Osuna is a FIWARE Expert in FIWARE Space iHub, developing training (focused on colleges/universities students) and mentoring (startups, enterprises). Osuna is also the creator of hackatons related to FIWARE concepts and he is linked with LATAM iHubs and enterprises. In addition, he is a speaker at Fiware Global Summits and the leader of 2023 WorkGroup 1: Improving iHubs ecosystem. Osuna has a personal commitment on connecting people and iHubs. With an academic base of industrial engineering, industry 4.0, and innovation and digital transformation and personal involvement in maker, communities events, he has 25 years of experience in many areas linked to I+D and Technology.", linkedin: "https://www.linkedin.com/in/jorge-antonio-osuna-pons/", twitter: "https://twitter.com/jorgeosuna666", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Jem Pagán", img: "https://www.fiware.org/wp-content/directories/people/images/200px/jem-pagan.jpg", position: "Chief Executive Officer", company: "BluSky Consulting", "company-link": "https://blusky.me",
    content: "", linkedin: "https://www.linkedin.com/in/jempagan?miniProfileUrn&#x3D;urn%3Ali%3Afs_miniProfile%3AACoAAAEN7QwBkRUnDluYd32Id_e4VOhz8Qp2UO0&amp;lipi&#x3D;urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3B5ajmqlkVSHCnpV4BnSlz%2Fw%3D%3D", twitter: "https://twitter.com/jempagan", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Piotr Pawałowski", img: "https://www.fiware.org/wp-content/directories/people/images/200px/piotr-pawalowski.png", position: "Researcher", company: "Poznan Supercomputing and Networking Center", "company-link": "http://www.man.poznan.pl",
    content: "", linkedin: "https://www.linkedin.com/in/astagor?miniProfileUrn&#x3D;urn%3Ali%3Afs_miniProfile%3AACoAAAAqNGgBYH8ltfrZO8Pt92x31pmefcIDun0&amp;lipi&#x3D;urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3BekcNg2MWTRigFuUqlsAmuw%3D%3D", twitter: "https://twitter.com/Astagor", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Francisco Javier Peralta López", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francisco-javier-peralta-lopez.jpg", position: "Project Manager", company: "Telefónica S.A.", "company-link": "https://www.telefonica.com/en/",
    content: "", linkedin: "https://www.linkedin.com/in/fjperalta/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Irene Provvidenza", img: "https://www.fiware.org/wp-content/directories/people/images/200px/irene-provvidenza.jpg", position: "International Business Developer", company: "TeamDev SRL", "company-link": "https://teamdevecosystem.it/en/",
    content: "", linkedin: "https://www.linkedin.com/in/irene-provvidenza/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Gianluigi Riccio", img: "https://www.fiware.org/wp-content/directories/people/images/ico_user.png", position: "Digital Engineer", company: "Meditech Competence Center", "company-link": "https://meditech4.com",
    content: "", linkedin: "https://www.linkedin.com/in/gianluigi-riccio-609532b/", twitter: "https://twitter.com/RiccioGL", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Prof. Joaquín Salvachúa", img: "https://www.fiware.org/wp-content/directories/people/images/200px/joaquin-salvachua.jpg", position: "Professor", company: "Universidad Politécnica de Madrid", "company-link": "https://www.upm.es/internacional",
    content: "Prof. Joaquín Salvachúa received a master degree in Computer Science. He holds the Orange Chair for the “Science of Complex Networks” and the Kairos Chair on “Bank Middleware and Blockchain” at UPM and is a member of the UPM-ING and CyberAula groups. He has participated in several European research projects with several publications at international magazines, books and conferences. (https://orcid.org/0000-0002-7269-8079). Also have participated in several standardization activities, including been coauthor one RFC ( RFC 8802 ).His research focuses today on WebRTC, Cloud infrastructure, social graphs and recommendation, agile cloud infrastructures, P2P, DHT (Distributed HashTables), IOT, Non SQL Data Bases, Big data processing architectures, Identity Management and BlockChain distributed agreement algorithms.His teaching duties includes cloud computing, distributed application development, Databases, Web Full-stack development, Blockchain architecture, Data Engineering and Big data architecture and applications. Has been involved in the FIWARE Initiative since it started (2010) and he is architect and developer of several GE related to security, data persistence and Big Data analysis.", linkedin: "https://es.linkedin.com/in/jsalvachua", twitter: "https://twitter.com/jsalvachua", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Shuhei Sassano", img: "https://www.fiware.org/wp-content/directories/people/images/200px/shuhei-sassano.jpg", position: "Business Developer", company: "NEC Corporation", "company-link": "https://jpn.nec.com/",
    content: "I led the establishment of iHub Base, the first FIWARE iHub in Japan, and as a member of NEC, one of the platinum members of the FIWARE Foundation, I have worked hard to promote FIWARE and create a FIWARE community in Japan. When it comes to iHub Base&#x27;s activities including holding webinars, I have tried to increase the number of people who are interested in FIWARE.", linkedin: "https://www.linkedin.com/in/shuheisasano/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "David Seoane", img: "https://www.fiware.org/wp-content/directories/people/images/200px/david-seoane.jpg", position: "Head of Communities", company: "FundingBox", "company-link": "https://fundingbox.com/",
    content: "Over 12 years of experience in Fundraising in EU programs, Since, 2020, responsible for the Community Building Strategy across all European and private projects managed by FundingBox, curating the FundingBox Spaces database (+45k users).", linkedin: "https://www.linkedin.com/in/davidseoane/", twitter: "https://twitter.com/davidseoanevila", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Satinder Jeet Singh", img: "https://www.fiware.org/wp-content/directories/people/images/200px/satinder-jeet-singh.jpg", position: "Associate General Manager", company: "NEC Corporation India", "company-link": "https://in.nec.com/",
    content: "", linkedin: "https://www.linkedin.com/in/satinder-jeet-singh-a217587/", twitter: "https://twitter.com/satinderjs", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Kazuhito Suda", img: "https://www.fiware.org/wp-content/directories/people/images/200px/kazuhito-suda.jpg", position: "Senior Developer", company: "FIWARE", "company-link": "https://www.fiware.org",
    content: "", linkedin: "", twitter: "https://twitter.com/kz_suda", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Anna Szterenfeld", img: "https://www.fiware.org/wp-content/directories/people/images/200px/anna-szterenfeld.jpg", position: "Editorial Director", company: "ThoughtLab Group", "company-link": "https://thoughtlabgroup.com/",
    content: "ThoughtLab has worked with Fiware Foundation on previous research studies about smart cities. Fiware was a valuable association partner of our last study, Building a Future-Ready City, and we recognize the importance of open source solutions and ecosystems to the future success of cities, especially small cities with limited budgets. ThoughtLab supports Fiware&#x27;s efforts and we are happy to collaborate with it as Evangelists.", linkedin: "https://www.linkedin.com/in/annaszterenfeld/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Sanaa Tazi", img: "https://www.fiware.org/wp-content/directories/people/images/200px/sanaa-tazi.jpg", position: "CEO &amp; Co-Finder", company: "African Smart Territories", "company-link": "https://mnc.ma/en/accueil-english/",
    content: "Moroccan &amp; African Digital hub and innovation booster : helps start-ups by providing free trainings, technical assistance, calls for applications, technology innovation support, events and networking. Helps the biggest with technology innovation support to succeed in their digital transformation. Try to change minds by empowering African Women in Tech and strengthening Minority small businesses.", linkedin: "https://www.linkedin.com/in/sanaa-tazi-15579174/", twitter: "https://twitter.com/sanaa_tazi_", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Rahul Tomar", img: "https://www.fiware.org/wp-content/directories/people/images/200px/rahul-tomar.jpg", position: "Co-Founder", company: "DigitalTwin Technology", "company-link": "https://www.digitaltwin.technology/",
    content: "", linkedin: "https://www.linkedin.com/in/rahultomarpmp/", twitter: "https://twitter.com/rahul_606", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Gaetano Volpe", img: "https://www.fiware.org/wp-content/directories/people/images/200px/gaetano-volpe.jpg", position: "CEO", company: "Latitudo 40", "company-link": "https://www.latitudo40.com",
    content: "Gaetano Volpe, as the CEO of Latitudo 40 and an expert in space and smart cities solutions, likely considers himself a potential FIWARE Evangelist due to his extensive experience and expertise in fields closely aligned with FIWARE&#x27;s goals. FIWARE focuses on developing open-source standards for smart solutions in various sectors, including cities and space technology, which aligns well with the work Volpe does at Latitudo 40. Being deeply involved in leveraging geospatial data analytics for urban planning and environmental monitoring, Volpe&#x27;s expertise positions him well to advocate for FIWARE’s open, standards-based platforms. His role at Latitudo 40 likely involves working with technologies and principles that are at the core of FIWARE&#x27;s mission, such as IoT, AI, and big data, all crucial for smart city applications and space-based data analysis. As a recognized FIWARE Evangelist, Volpe would have the opportunity to further promote the integration of open-source technologies in smart city and space solutions, influencing wider adoption and innovation in these sectors. His background and leadership in a company that specializes in cutting-edge geospatial analytics make him a strong candidate for such a role, where he can share insights, foster collaborations, and drive forward the vision of a more interconnected and intelligent approach to urban and environmental challenges.", linkedin: "https://www.linkedin.com/in/dario-avallone-428934a/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Aleksandar Vrglevski", img: "https://www.fiware.org/wp-content/directories/people/images/200px/aleksandar-vrglevski.jpg", position: "Technology Expert", company: "Vienna Business Agency", "company-link": "https://viennabusinessagency.at/",
    content: "Aleksandar Vrglevski has been involved in blockchain research since 2016 and is especially interested in privacy-related projects, which he was researching on as a part of the RIAT institute. Nowadays he is the focal person for Blockchain, Fintech as well as Open Source at the Vienna Business Agency and an active contributor for the FIWARE DACH-Community.", linkedin: "https://www.linkedin.com/in/avrglevski/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Yasunori Mochizuki", img: "https://www.fiware.org/wp-content/directories/people/images/200px/yasunori-mochizuki.jpg", position: "NEC Fellow", company: "NEC Corporation", "company-link": "https://www.nec.com/",
    content: "", linkedin: "https://www.linkedin.com/in/yasunori-mochizuki-93bab674/?originalSubdomain&#x3D;jp", twitter: "https://twitter.com/YasunoriMochiz", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
    { name: "Ken Zangelin", img: "https://www.fiware.org/wp-content/directories/people/images/200px/ken-zangelin.jpg", position: "Senior Technical Expert &amp; Evangelist", company: "FIWARE Foundation e.V.", "company-link": "https://www.fiware.org/",
    content: "", linkedin: "https://www.linkedin.com/in/kzangeli/", twitter: "", domain: "", location: "",
    flag: "https://www.fiware.org/wp-content/directories/people/images/flag", },
];