var companies = [];
var departments = [];
var titles = [
        'Africa',
        'Asia-Pacific',
        'Central America',
        'Europe',
        'Latin America',
        'Middle East',
        'North America',
]; var domains = [
]; var countries = [
        'Argentina',
        'Australia',
        'Austria',
        'Belgium',
        'Brazil',
        'Canada',
        'Colombia',
        'Croatia',
        'Denmark',
        'Finland',
        'France',
        'Germany',
        'Greece',
        'India',
        'Italy',
        'Japan',
        'Malaysia',
        'Mexico',
        'Monaco',
        'Morocco',
        'Netherlands',
        'Panama',
        'Peru',
        'Poland',
        'Portugal',
        'Romania',
        'Saudi Arabia',
        'Senegal',
        'Spain',
        'Sweden',
        'Switzerland',
        'United Kingdom',
        'Uruguay',
        'USA',
]; 
