var companies = [];
var departments = [];
var titles = [
        '2020',
        '2021',
        '2022',
        '2023',
        '2024',
        '2025',
]; var domains = [
        'AgriFood',
        'AgriTech',
        'Blue Economy',
        'Buildings',
        'Cities',
        'eGovernance',
        'eHealth',
        'Energy',
        'Environment',
        'Industry',
        'Islands',
        'Logistics',
        'Manufacturing',
        'Mobility',
        'Ports',
        'Robotics',
        'Spaces',
        'Street Lighting',
        'Sustainability',
        'Tourism',
        'Water',
]; var countries = [
        'Deutsch',
        'English',
        'Español',
        'Français',
        'Italiano',
]; 
