var types = [
    'Core Context',
    'Cross-Chapter',
    'Data Monetization',
    'Fundamentals',
    'IoT Agents',
    'Operations',
    'Processing',
    'Robotics',
    'Security',
    'Visualisation'
];
var domains = ['Business', 'Community', 'Developers', 'iHubs'];
var technologies = [
    'Agrifood',
    'AI',
    'Apache Flink',
    'Apache Flume',
    'Apache NIFI',
    'Apache Spark',
    'API Umbrella',
    'Blockchain',
    'Business Ecosystem',
    'Canis Major',
    'Cities',
    'Cosmos',
    'Cygnus',
    'Data Models',
    'DDS',
    'Draco',
    'FIROS',
    'FogFlow',
    'Grafana',
    'IoT Agent',
    'IOTA Tangle',
    'Keyrock',
    'microROS',
    'MLOps',
    'NGSI-LD',
    'NGSI-v2',
    'Pyspark',
    'QuantumLeap',
    'ROS',
    'STH-Comet',
    'Water',
    'Wirecloud'
];
