var departments = [
        'Hands-On Use Cases',
        'Innovation with FIWARE',
        'Tech &amp; Trends',
]; var domains = [
        'Data Space Technology',
        'Digital Twins',
        'FISAB &amp; Universities',
        'Innovation projects on data interoperability',
        'Innovation projects on data platforms and Data Spaces',
        'Innovation projects on green and industry digital twins',
        'Smart Communities &amp; Mobility',
        'Smart Energy',
];
var technologies = [
        'Alberto Abella',
        'Ulrich Ahle',
        'Andrea Battaglia',
        'Martin Bauer',
        'Ali Benrahim',
        'Massimo Bertoncini',
        'Sebastian Blechmann',
        'Ilaria Bortone',
        'David Campo',
        'Javier Conde',
        'Mireya de Diego',
        'Stefano De Panfilis',
        'Roberto Di Bernardo',
        'Gregory Eve',
        'Antonio Filograna',
        'Juanjo Hierro',
        'Antonio Jara',
        'Ernoe Kovacs',
        'Frédéric Le',
        'Franck Le Gall',
        'Antonella Longo',
        'Angelo Marguglio',
        'Nejib Moalla',
        'Yasunori Mochizuki',
        'Antonello Monti',
        'Luis Muñoz',
        'José A. Muñoz Arcentales',
        'Francesco Mureddu',
        'Robyn Lesley Oldfield',
        'Fabiano Pallonetto',
        'Mads Pohl Petersson',
        'Clara Pezuela',
        'Manfredi Pistone',
        'Michael Prange',
        'Matteo Repetto',
        'Ana Garcia Robles',
        'Jesús Ruiz Martinez',
        'Joaquín Salvachúa',
        'Raúl Sánchez-Mateos Lizano',
        'Laura Ileana Schipani',
        'Giovanni Vaglica',
        'Gaetano Volpe',
        'Dennis Wendland',
        'Stefan Wiedemann',
];
