var companies = [
        'FIWARE Foundation',
]; var departments = [
        'Operations',
        'Technical',
]; var domains = [
]; var titles = [
]; var countries = [
]; var modalData = [
    { name: "Alberto Abella", img: "https://www.fiware.org/wp-content/directories/people/images/200px/alberto-abella.jpg", position: "Coordination of Smart Data Models Initiative", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Alberto Abella (m) is PhD in Business (Open data) and Telecommunications Engineer and Master in Total Quality Management, Business Administration and Business Organization. He works as a Data Modelling Expert and Technical Evangelist at FIWARE and currently is the responsible person for the smart data models initiative.", linkedin: "https://www.linkedin.com/in/albertoabella/", twitter: "https://twitter.com/aabella", domain: "", location: ""
    },
    { name: "Chandra Challagonda", img: "https://www.fiware.org/wp-content/directories/people/images/200px/chandra-challagonda.jpg", position: "Chief Executive Officer", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Chandra Challagonda has 26 years of experience in the technology industry, focusing on Machine Learning, Artificial Intelligence, and open-source technologies. Recognized as a business transformer, he emphasizes innovation and customer-centric strategies in executive roles such as Co-Founder, Board Member, CEO, and CTO. Over the last year, Chandra was working as a FIWARE community and board member, architect and Vice President, growing its global network and ecosystem and helping to develop sustainable strategies and partnerships in the organisation.", linkedin: "https://linkedin.com/in/challagonda", twitter: "https://twitter.com/challagonda", domain: "", location: ""
    },
    { name: "Viktoryia Danilenko", img: "https://www.fiware.org/wp-content/directories/people/images/200px/viktoryia-danilenko.jpg", position: "Administration and Accounting", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "11 years of experience in the aviation industry, Viktoryia Danilenko (f) was responsible for the professional organisation and management of passenger operations. The work required great diligence, attention and concentration. Effectively co-operated with different departments and services of the airline.The most significant achievements are independent work in the process of opening new flights according to all technical and legal aspects, as well as the support of the management during this period. Viktoryia constantly strives to improve her professional level and to be attentive to details, she values teamwork and mutual assistance as part of the organizational culture.", linkedin: "https://www.linkedin.com/in/viktoryia-danilenko-b664a62a8/", twitter: "", domain: "", location: ""
    },
    { name: "Charlotte Kotterman", img: "https://www.fiware.org/wp-content/directories/people/images/200px/charlotte-kotterman.jpg", position: "Senior Community Manager", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "With over 8 years of experience in Marketing, Community Building, and Social Media Management activities, Charlotte Kotterman (f) has supported numerous communities to grow and thrive. She has managed content calendars, curated content, as well as produced relevant and engaging content for social media (Facebook, Twitter, Linkedin, Tumblr, Instagram), community emails, newsletters, and websites. With FIWARE Foundation since 2017, she has been involved in numerous EU projects supporting the dissemination of relevant project and technical information through the FIWARE channels while at the same time leading strategic Social Media projects. She has led monthly Community Marketing Calls, several publications, and community webinars. Her portfolio of responsibilities includes the curation and growth of FIWARE Marketplace. Charlotte holds a Master of Arts (MA) in German and Management Studies (Joint Honours) from the University of Aberdeen, Scotland.", linkedin: "https://de.linkedin.com/in/charlottekotterman", twitter: "https://twitter.com/char_kotterman", domain: "", location: ""
    },
    { name: "Francisco Meléndez", img: "https://www.fiware.org/wp-content/directories/people/images/200px/francisco-melendez.jpg", position: "FIWARE Technical Community Support and Engagement", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Francisco Melendez (m) is a Telecommunications &amp; Robotics Engineer and is FIWARE’s Technical Expert in Robotics, Automation and Industry 4.0. He is also one of the representatives of FIWARE in the Digital Twin Consortium and some international projects where FIWARE is developing its technical roadmap in robotics and automation. As a mobile robotics engineer and researcher with more than 8 years of experience in web-enabled robot applications, his work is currently focused on the development of convenient interfaces between cyber physical systems and digital twins in FIWARE-based solutions.", linkedin: "https://www.linkedin.com/in/franmelfer/", twitter: "", domain: "", location: ""
    },
    { name: "Ángeles Tejado", img: "https://www.fiware.org/wp-content/directories/people/images/200px/angeles-tejado.jpg", position: "FIWARE iHubs Support and Engagement", company: "FIWARE Foundation", "company-link": "https://www.fiware.org/",
    content: "Angeles Tejado (f) holds a degree in Biochemistry (Autonomous University Madrid), Fine Arts (Complutense University Madrid) and a Master Degree in Scientific-Technical Documentation (Spanish National Research Council - CSIC). She has +20 year experience working in multinationals such as Havas Group and Ogilvy &amp; Mather in global account management and integrated marketing communication for companies in the pharmaceutical, healthcare and tech (e.g., IBM) sectors among others. In 2013 she started coordinating communications and ecosystem building activities for FIWARE at Ogilvy, joining the FIWARE Foundation in 2017 to contribute to FIWARE Go-to-market, Ecosystem Building and Community Engagement activities through participation in different FIWARE Mission Support Committees, collaborating in the kick-start of several FIWARE Strategic Programmes, the organization of several FIWARE Summits and presence of FIWARE in fairs as well as supporting the planning and execution of the FIWARE Communication Strategy. She also has a deep experience in EU Projects as Communication and Ecosystem building Work Package leader (microROS, Token, Cattlechain, GUARD, i4Trust) and Task Leader (FIWARE4Water, Boost4.0, Connected Car). She is currently holding the role of Senior Program Manager contributing to the expansion and growth of the FIWARE Innovation Hubs network worldwide.", linkedin: "https://www.linkedin.com/in/%C3%A1ngeles-tejado-s%C3%A1nchez-2a61b411/", twitter: "", domain: "", location: ""
    }
];