name: Publish PRODUCTS to LIVE fiware.org/showcase

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: copy file via sftp
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          uploads: |
            marketplace/ => ${{ secrets.SSH_DIR }}/marketplace/
            showcase/ => ${{ secrets.SSH_DIR }}/showcase/
